
import type { WorkerRecord, SafetyCheckRecord, HandwrittenAnswer } from './types';

// 예시 데이터 생성 함수 및 데이터 소스는 유지하되, 
// 실제 앱 실행 시에는 빈 배열을 반환하도록 설정합니다.
// 필요 시 테스트를 위해 이 파일의 mockWorkerRecords 배열을 채울 수 있습니다.

const jobFields = ['시스템', '용역', '철근', '분석', '배체정리', '형틀'];
const nationalities = ['베트남', '중국', '한국', '태국', '캄보디아', '몽골', '카자흐스탄'];

// Empty arrays to start fresh
export const mockWorkerRecords: WorkerRecord[] = [];
export const mockSafetyCheckRecords: SafetyCheckRecord[] = [];

type QaSeedRecord = Record<string, unknown>;

const createQaAnswers = (nativeLines: [string, string, string, string, string]): Array<{ questionNumber: string; answerText: string; koreanTranslation: string; nativeTranslation: string }> => [
	{
		questionNumber: '1',
		answerText: '고소 작업 시 추락 위험이 가장 큽니다.',
		koreanTranslation: '고소 작업 시 추락 위험이 가장 큽니다.',
		nativeTranslation: nativeLines[0],
	},
	{
		questionNumber: '2',
		answerText: '안전대 미체결, 작업 전 점검 누락이 가장 큰 위험요소입니다.',
		koreanTranslation: '안전대 미체결, 작업 전 점검 누락이 가장 큰 위험요소입니다.',
		nativeTranslation: nativeLines[1],
	},
	{
		questionNumber: '3',
		answerText: '상',
		koreanTranslation: '상',
		nativeTranslation: nativeLines[2],
	},
	{
		questionNumber: '4',
		answerText: '작업 전 안전벨트 체결 상태를 반드시 확인하겠습니다.',
		koreanTranslation: '작업 전 안전벨트 체결 상태를 반드시 확인하겠습니다.',
		nativeTranslation: nativeLines[3],
	},
	{
		questionNumber: '5',
		answerText: '매일 작업 시작 전에 팀장과 위험요소를 확인하겠습니다.',
		koreanTranslation: '매일 작업 시작 전에 팀장과 위험요소를 확인하겠습니다.',
		nativeTranslation: nativeLines[4],
	},
];

export const qaBilingualWorkerSeedRecords: QaSeedRecord[] = [
	{
		id: 'qa-vn-001',
		name: '응우옌 반 민',
		nationality: '베트남',
		language: 'vi',
		jobField: '골조',
		teamLeader: '이태호',
		date: '2026-04-21',
		safetyScore: 88,
		safetyLevel: '고급',
		strengths: ['고소작업 위험 인지 수준이 높음'],
		strengths_native: ['Nhận thức tốt về nguy cơ làm việc trên cao'],
		weakAreas: ['안전대 체결 재확인 습관 필요'],
		weakAreas_native: ['Cần hình thành thói quen kiểm tra lại dây an toàn'],
		improvement: '작업 시작 전 체크리스트 확인',
		improvement_native: 'Kiểm tra checklist trước khi bắt đầu công việc',
		aiInsights: '고소 작업에서 추락 방지를 위해 안전대 체결과 작업 전 점검을 반복 확인해야 합니다.',
		aiInsights_native: 'Để phòng ngã khi làm việc trên cao, cần kiểm tra lại dây an toàn và điểm kiểm tra trước ca.',
		actionable_coaching: '작업 전/중/후로 나누어 위험요소를 확인하고 팀장 확인 후 작업하세요.',
		actionable_coaching_native: 'Chia theo trước/trong/sau khi làm để kiểm tra rủi ro và xác nhận với đội trưởng.',
		handwrittenAnswers: createQaAnswers([
			'Nguy cơ lớn nhất là rơi ngã khi làm việc trên cao.',
			'Không cài dây an toàn và bỏ qua kiểm tra trước ca là yếu tố nguy hiểm nhất.',
			'Cao',
			'Tôi sẽ luôn kiểm tra tình trạng cài dây an toàn trước khi làm.',
			'Mỗi ngày trước giờ làm, tôi sẽ kiểm tra rủi ro cùng đội trưởng.',
		]),
	},
	{
		id: 'qa-cn-001',
		name: '리웨이',
		nationality: '중국',
		language: 'zh',
		jobField: '철근',
		teamLeader: '박정민',
		date: '2026-04-21',
		safetyScore: 84,
		safetyLevel: '고급',
		strengths: ['위험요인 식별이 정확함'],
		strengths_native: ['风险识别准确'],
		weakAreas: ['작업 전 장비 점검 기록 보강 필요'],
		weakAreas_native: ['需要加强作业前设备检查记录'],
		improvement: '점검 항목 기록 후 팀장 확인',
		improvement_native: '记录检查项目后由班组长确认',
		aiInsights: '철근 작업 시 협착과 낙하물 위험이 크므로 작업 전 점검 기록을 구체화해야 합니다.',
		aiInsights_native: '钢筋作业中夹伤和坠物风险较大，需要细化作业前检查记录。',
		actionable_coaching: '작업 전 체크·작업 중 통제·작업 후 재점검을 순서대로 지키세요.',
		actionable_coaching_native: '请按“作业前检查-作业中管控-作业后复检”的顺序执行。',
		handwrittenAnswers: createQaAnswers([
			'高处作业时坠落风险最大。',
			'未系安全带和遗漏作业前检查是最大风险因素。',
			'高',
			'作业前我会确认安全带固定状态。',
			'每天作业开始前我会与班组长确认风险点。',
		]),
	},
	{
		id: 'qa-th-001',
		name: '솜차이',
		nationality: '태국',
		language: 'th',
		jobField: '형틀',
		teamLeader: '김도현',
		date: '2026-04-20',
		safetyScore: 81,
		safetyLevel: '고급',
		strengths: ['작업 순서 준수 의지가 강함'],
		strengths_native: ['มีความตั้งใจในการปฏิบัติตามลำดับงานสูง'],
		weakAreas: ['보호구 착용 확인 누락 가능성'],
		weakAreas_native: ['มีโอกาสพลาดการยืนยันการสวมอุปกรณ์ป้องกัน'],
		improvement: '작업 전 보호구 체크리스트 작성',
		improvement_native: 'ทำเช็กลิสต์อุปกรณ์ป้องกันก่อนเริ่มงาน',
		aiInsights: '형틀 작업에서는 추락·충돌 예방을 위해 보호구 착용 확인을 수시로 반복해야 합니다.',
		aiInsights_native: 'งานแบบหล่อมีความเสี่ยงตกและชน จึงต้องยืนยันการสวมอุปกรณ์ป้องกันซ้ำๆ',
		actionable_coaching: '팀 단위로 작업 전 위험요소를 확인하고 역할을 분담해 점검하세요.',
		actionable_coaching_native: 'ตรวจสอบความเสี่ยงก่อนงานเป็นทีม และแบ่งหน้าที่ตรวจสอบให้ชัดเจน',
		handwrittenAnswers: createQaAnswers([
			'ความเสี่ยงสูงสุดคือการตกจากที่สูง',
			'ไม่คาดเข็มขัดนิรภัยและไม่ตรวจสอบก่อนงานคือปัจจัยเสี่ยงหลัก',
			'สูง',
			'ก่อนเริ่มงานผมจะตรวจสอบการคาดเข็มขัดนิรภัยทุกครั้ง',
			'ทุกวันก่อนเริ่มงานจะยืนยันความเสี่ยงกับหัวหน้าทีม',
		]),
	},
	{
		id: 'qa-kh-001',
		name: '소반',
		nationality: '캄보디아',
		language: 'km',
		jobField: '배관',
		teamLeader: '최민수',
		date: '2026-04-19',
		safetyScore: 79,
		safetyLevel: '중급',
		strengths: ['작업 위험요소를 잘 기억함'],
		strengths_native: ['ចងចាំហានិភ័យការងារបានល្អ'],
		weakAreas: ['작업 중 통제선 유지 습관 필요'],
		weakAreas_native: ['ត្រូវបង្កើនទម្លាប់រក្សាខ្សែគ្រប់គ្រងពេលធ្វើការ'],
		improvement: '작업 구역 통제선 재확인',
		improvement_native: 'ពិនិត្យឡើងវិញខ្សែគ្រប់គ្រងតំបន់ការងារ',
		aiInsights: '배관 작업 구역에서 충돌·협착 위험을 줄이기 위해 통제선 관리가 중요합니다.',
		aiInsights_native: 'ក្នុងតំបន់ការងារបំពង់ ត្រូវគ្រប់គ្រងខ្សែគ្រប់គ្រងឱ្យបានតឹងរ៉ឹង ដើម្បីកាត់បន្ថយការប៉ះទង្គិច និងការជាប់គាំង។',
		actionable_coaching: '작업 전 통제선·진입 동선을 먼저 확인한 뒤 작업을 시작하세요.',
		actionable_coaching_native: 'មុនចាប់ផ្តើមការងារ សូមពិនិត្យខ្សែគ្រប់គ្រង និងផ្លូវចូលចេញជាមុនសិន',
		handwrittenAnswers: createQaAnswers([
			'ហានិភ័យធំបំផុតគឺការធ្លាក់ពីទីខ្ពស់',
			'មិនពាក់ខ្សែក្រវ៉ាត់សុវត្ថិភាព និងខកខានពិនិត្យមុនការងារ គឺជាហានិភ័យសំខាន់',
			'ខ្ពស់',
			'មុនធ្វើការ ខ្ញុំនឹងពិនិត្យការចាក់សោរខ្សែក្រវ៉ាត់សុវត្ថិភាពរាល់ពេល',
			'រៀងរាល់ថ្ងៃ មុនចាប់ផ្តើមការងារ ខ្ញុំនឹងពិនិត្យហានិភ័យជាមួយមេក្រុម',
		]),
	},
	{
		id: 'qa-id-001',
		name: '아궁',
		nationality: '인도네시아',
		language: 'id',
		jobField: '전기',
		teamLeader: '오재훈',
		date: '2026-04-19',
		safetyScore: 82,
		safetyLevel: '고급',
		strengths: ['전기 위험요소를 명확히 인지'],
		strengths_native: ['Memahami bahaya listrik dengan jelas'],
		weakAreas: ['작업 전 절연 상태 점검 강화 필요'],
		weakAreas_native: ['Perlu memperkuat pemeriksaan kondisi isolasi sebelum kerja'],
		improvement: '절연장갑·절연공구 체크 강화',
		improvement_native: 'Perkuat pengecekan sarung tangan dan alat berisolasi',
		aiInsights: '전기 작업에서는 감전 위험 예방을 위해 절연 상태와 차단 조치를 먼저 확인해야 합니다.',
		aiInsights_native: 'Dalam pekerjaan listrik, pencegahan sengatan membutuhkan cek isolasi dan tindakan pemutusan terlebih dahulu.',
		actionable_coaching: '작업 전 차단 확인 후 공구 상태를 점검하고 작업을 시작하세요.',
		actionable_coaching_native: 'Sebelum kerja, konfirmasi pemutusan lalu cek kondisi alat sebelum mulai.',
		handwrittenAnswers: createQaAnswers([
			'Risiko terbesar adalah jatuh saat bekerja di ketinggian.',
			'Tidak mengaitkan sabuk keselamatan dan melewatkan pengecekan awal adalah faktor risiko utama.',
			'Tinggi',
			'Sebelum bekerja saya akan selalu memeriksa pengait sabuk keselamatan.',
			'Setiap hari sebelum mulai kerja saya akan konfirmasi risiko dengan ketua tim.',
		]),
	},
	{
		id: 'qa-mn-001',
		name: '바타르',
		nationality: '몽골',
		language: 'mn',
		jobField: '미장',
		teamLeader: '한영수',
		date: '2026-04-18',
		safetyScore: 77,
		safetyLevel: '중급',
		strengths: ['작업 절차 이해가 높음'],
		strengths_native: ['Ажлын дарааллын ойлголт сайн'],
		weakAreas: ['작업 중 위험 재평가 빈도 보강 필요'],
		weakAreas_native: ['Ажлын явц дахь эрсдэлийн дахин үнэлгээг нэмэгдүүлэх шаардлагатай'],
		improvement: '작업 중 변화 발생 시 즉시 재평가',
		improvement_native: 'Ажлын нөхцөл өөрчлөгдвөл даруй дахин үнэлэх',
		aiInsights: '미장 작업 구역에서는 전도·충돌 위험을 줄이기 위해 이동 동선 점검이 필요합니다.',
		aiInsights_native: 'Шавардлагын бүсэд бүдрэх, мөргөлдөх эрсдэлийг бууруулахын тулд хөдөлгөөний замыг шалгах шаардлагатай.',
		actionable_coaching: '작업 구간 이동 전 바닥 상태와 장애물을 먼저 확인하세요.',
		actionable_coaching_native: 'Ажлын хэсгээр шилжихийн өмнө шалны нөхцөл ба саадыг эхэлж шалга.',
		handwrittenAnswers: createQaAnswers([
			'Өндөрт ажиллах үед унах эрсдэл хамгийн их.',
			'Аюулгүйн бүсээ зүүхгүй байх, ажлын өмнөх шалгалтыг алгасах нь хамгийн том эрсдэл.',
			'Өндөр',
			'Ажил эхлэхийн өмнө бүсний түгжээг заавал шалгана.',
			'Өдөр бүр ажлын өмнө багийн ахлагчтай эрсдэлийг нягтална.',
		]),
	},
	{
		id: 'qa-ru-001',
		name: '이반',
		nationality: '러시아',
		language: 'ru',
		jobField: '시스템',
		teamLeader: '윤석진',
		date: '2026-04-18',
		safetyScore: 80,
		safetyLevel: '고급',
		strengths: ['점검 절차 숙지가 우수함'],
		strengths_native: ['Хорошо знает процедуры проверки'],
		weakAreas: ['작업 후 정리·정돈 항목 보강 필요'],
		weakAreas_native: ['Нужно усилить пункт уборки и порядка после работы'],
		improvement: '작업 후 정리 체크리스트 작성',
		improvement_native: 'Вести чек-лист уборки после работы',
		aiInsights: '시스템 작업 후 정리 상태가 다음 공정 안전에 직접 영향을 줍니다.',
		aiInsights_native: 'Состояние уборки после системных работ напрямую влияет на безопасность следующего этапа.',
		actionable_coaching: '작업 종료 후 잔재물·공구 정리를 표준 순서로 확인하세요.',
		actionable_coaching_native: 'После завершения работ проверяйте порядок остатков и инструментов по стандартной последовательности.',
		handwrittenAnswers: createQaAnswers([
			'Самый большой риск — падение при работе на высоте.',
			'Не пристёгнутый страховочный пояс и пропуск предсменной проверки — главный фактор риска.',
			'Высокий',
			'Перед работой я обязательно проверю фиксацию страховочного пояса.',
			'Каждый день перед началом работы я проверю риски с бригадиром.',
		]),
	},
	{
		id: 'qa-kz-001',
		name: '아슬란',
		nationality: '카자흐스탄',
		language: 'kk',
		jobField: '골조',
		teamLeader: '정성우',
		date: '2026-04-17',
		safetyScore: 80,
		safetyLevel: '고급',
		strengths: ['위험 식별 체크가 성실함'],
		strengths_native: ['Қауіпті анықтау тексерісін мұқият орындайды'],
		weakAreas: ['작업 중 통신 확인 단계 보강 필요'],
		weakAreas_native: ['Жұмыс кезіндегі байланыс тексеру кезеңін күшейту қажет'],
		improvement: '신호·무전 확인을 작업 전 고정 절차화',
		improvement_native: 'Сигнал және рация тексеруін жұмыс алдындағы тұрақты рәсімге енгізу',
		aiInsights: '골조 작업에서는 통신 누락이 충돌 위험으로 이어질 수 있어 신호 확인이 중요합니다.',
		aiInsights_native: 'Қаңқа жұмыстары кезінде байланыс үзілуі соқтығысу қаупіне әкелуі мүмкін, сондықтан сигналды тексеру маңызды.',
		actionable_coaching: '작업 전 신호체계와 통신 상태를 팀 단위로 점검하세요.',
		actionable_coaching_native: 'Жұмыс алдында сигнал жүйесі мен байланыс күйін топпен тексеріңіз.',
		handwrittenAnswers: createQaAnswers([
			'Ең үлкен қауіп — биіктікте жұмыс істегенде құлау.',
			'Қауіпсіздік белдігін тақпау және жұмыс алдындағы тексеруді өткізіп жіберу — негізгі қауіп факторы.',
			'Жоғары',
			'Жұмыс алдында қауіпсіздік белдігінің бекітілуін міндетті түрде тексеремін.',
			'Күн сайын жұмыс басталар алдында тәуекелді топ жетекшісімен тексеремін.',
		]),
	},
	{
		id: 'qa-mm-001',
		name: '아웅민',
		nationality: '미얀마',
		language: 'my',
		jobField: '형틀',
		teamLeader: '강태민',
		date: '2026-04-17',
		safetyScore: 83,
		safetyLevel: '고급',
		strengths: ['위험요인 인식이 빠름'],
		strengths_native: ['အန္တရာယ်ကို လျင်မြန်စွာ သိရှိနိုင်သည်'],
		weakAreas: ['작업 전 체크리스트 누락 방지 필요'],
		weakAreas_native: ['အလုပ်မစတင်မီ စစ်ဆေးစာရင်း မလွတ်စေရန် လိုအပ်သည်'],
		improvement: '작업 시작 전 체크리스트 확인 체계화',
		improvement_native: 'အလုပ်မစတင်မီ စစ်ဆေးစာရင်းကို စနစ်တကျ အတည်ပြုရန်',
		aiInsights: '형틀 작업에서는 추락·협착 위험 예방을 위해 사전점검 누락이 없어야 합니다.',
		aiInsights_native: 'ပုံစံတပ်ဆင်အလုပ်တွင် ပြုတ်ကျမှုနှင့် ဖိကြပ်မှုအန္တရာယ်ကို ကာကွယ်ရန် အလုပ်မစမီ စစ်ဆေးမှု မလွတ်စေရပါ။',
		actionable_coaching: '작업 전 체크-작업 중 점검-작업 후 정리를 반드시 반복하세요.',
		actionable_coaching_native: 'အလုပ်မစမီ စစ်ဆေးခြင်း၊ အလုပ်ချိန်အတွင်း စစ်ဆေးခြင်းနှင့် အလုပ်ပြီးနောက် စနစ်တကျသိမ်းဆည်းခြင်းကို အမြဲလုပ်ပါ။',
		auditTrail: [
			{
				timestamp: '2026-04-17T09:10:00+09:00',
				stage: 'reassessment',
				actor: 'SYSTEM',
				note: '[reassessment] Could not find table public.ai_workflow_run : UNKNOWN(uncategorized)',
			},
		],
		handwrittenAnswers: createQaAnswers([
			'အမြင့်တွင်အလုပ်လုပ်စဉ် ပြုတ်ကျမှုအန္တရာယ်သည် အကြီးဆုံးဖြစ်သည်။',
			'လုံခြုံရေးခါးပတ် မချိတ်ခြင်းနှင့် အလုပ်မစမီ စစ်ဆေးမှုမလုပ်ခြင်းသည် အကြီးမားဆုံးအန္တရာယ်ဖြစ်သည်။',
			'မြင့်',
			'အလုပ်မစမီ လုံခြုံရေးခါးပတ် ချိတ်ဆက်ထားမှုကို မဖြစ်မနေ စစ်ဆေးမည်။',
			'နေ့စဉ် အလုပ်မစမီ အဖွဲ့ခေါင်းဆောင်နှင့် အန္တရာယ်အချက်များကို စစ်ဆေးမည်။',
		]),
	},
	{
		id: 'qa-vn-002',
		name: '쩐 민 딴',
		nationality: '베트남',
		language: 'vi',
		jobField: '골조',
		teamLeader: '이태호',
		date: '2026-04-22',
		safetyScore: 86,
		safetyLevel: '고급',
		strengths: ['작업 전 점검 문장이 구체적임'],
		strengths_native: ['Câu mô tả kiểm tra trước ca khá cụ thể'],
		weakAreas: ['작업 중 확인 주기 명시 보강 필요'],
		weakAreas_native: ['Cần nêu rõ tần suất kiểm tra trong ca'],
		improvement: '작업 중 30분 단위 점검 루틴 명시',
		improvement_native: 'Nêu rõ chu kỳ kiểm tra mỗi 30 phút trong ca',
		aiInsights: '골조 작업에서 추락·낙하 위험을 줄이기 위해 작업 전 확인과 작업 중 점검 주기를 함께 명시해야 합니다.',
		aiInsights_native: 'Trong công tác kết cấu, cần nêu rõ cả kiểm tra trước ca và chu kỳ kiểm tra trong ca để giảm rủi ro ngã và vật rơi.',
		actionable_coaching: '작업 전 생명줄 체결 확인, 작업 중 30분 단위 점검, 작업 후 정리 순서를 지키세요.',
		actionable_coaching_native: 'Thực hiện theo thứ tự: kiểm tra dây cứu sinh trước ca, kiểm tra mỗi 30 phút trong ca, rồi dọn dẹp sau ca.',
		handwrittenAnswers: createQaAnswers([
			'Khi làm việc trên cao, nguy cơ ngã là lớn nhất.',
			'Không móc dây an toàn và bỏ qua kiểm tra đầu ca là nguy cơ chính.',
			'Cao',
			'Tôi sẽ kiểm tra móc khóa dây an toàn trước khi bắt đầu.',
			'Tôi sẽ rà soát điểm nguy hiểm với đội trưởng trước giờ làm.',
		]),
	},
	{
		id: 'qa-cn-002',
		name: '장하오',
		nationality: '중국',
		language: 'zh',
		jobField: '철근',
		teamLeader: '박정민',
		date: '2026-04-22',
		safetyScore: 82,
		safetyLevel: '고급',
		strengths: ['위험요인과 대책 연결이 비교적 명확함'],
		strengths_native: ['风险点与对策连接较明确'],
		weakAreas: ['작업 후 확인 단계 보완 필요'],
		weakAreas_native: ['需补强作业后确认步骤'],
		improvement: '작업 후 체결 상태 재확인 추가',
		improvement_native: '增加作业后对固定状态的复核',
		aiInsights: '철근 작업에서 협착·낙하물 위험을 줄이려면 작업 전 확인과 작업 후 복기 절차를 함께 유지해야 합니다.',
		aiInsights_native: '钢筋作业要降低夹伤和坠物风险，需要同时保持作业前确认和作业后复盘流程。',
		actionable_coaching: '작업 전 확인-작업 중 통제-작업 후 복기 순서를 체크리스트로 고정하세요.',
		actionable_coaching_native: '请将“作业前确认-作业中管控-作业后复盘”固定为检查清单。',
		handwrittenAnswers: createQaAnswers([
			'高处作业最大的风险是坠落。',
			'未系安全带和忽略开工前检查是主要风险因素。',
			'高',
			'开工前我会确认安全带挂点和锁扣状态。',
			'每天开工前我会和班组长确认当日风险点。',
		]),
	},
	{
		id: 'qa-th-002',
		name: '프라윳',
		nationality: '태국',
		language: 'th',
		jobField: '형틀',
		teamLeader: '김도현',
		date: '2026-04-22',
		safetyScore: 79,
		safetyLevel: '중급',
		strengths: ['작업 전 준비 단계 서술이 성실함'],
		strengths_native: ['อธิบายขั้นตอนเตรียมงานก่อนเริ่มได้ดี'],
		weakAreas: ['작업 중 재확인 타이밍이 모호함'],
		weakAreas_native: ['จังหวะการตรวจซ้ำระหว่างงานยังไม่ชัดเจน'],
		improvement: '작업 중 점검 타이밍(예: 30분) 명시',
		improvement_native: 'ระบุเวลาตรวจระหว่างงานให้ชัด (เช่น ทุก 30 นาที)',
		aiInsights: '형틀 작업에서 추락·충돌 예방을 위해 작업 중 점검 시점을 명확히 적는 것이 중요합니다.',
		aiInsights_native: 'งานแบบหล่อต้องระบุช่วงเวลาตรวจระหว่างงานให้ชัด เพื่อป้องกันการตกและการชน',
		actionable_coaching: '작업 전 보호구 확인, 작업 중 주기 점검, 작업 후 정리까지 한 흐름으로 기록하세요.',
		actionable_coaching_native: 'บันทึกให้ครบเป็นลำดับเดียว: ตรวจอุปกรณ์ก่อนงาน ตรวจซ้ำระหว่างงาน และจัดระเบียบหลังงาน',
		handwrittenAnswers: createQaAnswers([
			'ความเสี่ยงหลักคือการตกจากที่สูงระหว่างงานแบบหล่อ',
			'ไม่คาดเข็มขัดนิรภัยและไม่เช็กก่อนงานเป็นความเสี่ยงสำคัญ',
			'สูง',
			'ก่อนเริ่มงานฉันจะตรวจจุดยึดและการล็อกเข็มขัดนิรภัย',
			'ก่อนเริ่มงานทุกวันฉันจะทบทวนความเสี่ยงกับหัวหน้าทีม',
		]),
	},
	{
		id: 'qa-ru-002',
		name: '세르게이',
		nationality: '러시아',
		language: 'ru',
		jobField: '시스템',
		teamLeader: '윤석진',
		date: '2026-04-22',
		safetyScore: 81,
		safetyLevel: '고급',
		strengths: ['작업 절차 문장화가 체계적임'],
		strengths_native: ['Описание рабочей процедуры структурировано'],
		weakAreas: ['작업 후 확인 항목 세분화 필요'],
		weakAreas_native: ['Нужно детализировать пункты послерабочей проверки'],
		improvement: '작업 후 잔재물·도구 점검 항목 분리',
		improvement_native: 'Разделить пункты проверки остатков и инструмента после работы',
		aiInsights: '시스템 작업에서는 작업 후 정리 수준이 다음 공정 안전과 직접 연결되므로 확인 항목을 세분화해야 합니다.',
		aiInsights_native: 'В системных работах уровень уборки после смены напрямую влияет на безопасность следующего этапа, поэтому пункты проверки нужно детализировать.',
		actionable_coaching: '작업 전 점검-작업 중 통제-작업 후 정리 확인을 동일 포맷 체크리스트로 유지하세요.',
		actionable_coaching_native: 'Сохраняйте единый формат чек-листа: проверка до начала, контроль в процессе, уборка и подтверждение после работы.',
		handwrittenAnswers: createQaAnswers([
			'Главный риск при работе на высоте — падение.',
			'Не пристёгнутый страховочный пояс и пропуск проверки перед началом — ключевые риски.',
			'Высокий',
			'Перед работой я проверю точку крепления и замок страховочного пояса.',
			'Перед началом смены я подтвержу риски вместе с бригадиром.',
		]),
	},
];
