-- PSI public API security hardening (2026-07-17)
-- Apply with the service-role migrations before enabling the hardened gateway.

begin;

create table if not exists public.api_security_events (
    id bigint generated by default as identity primary key,
    scope text not null,
    client_key_hash text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists api_security_events_scope_client_created_idx
    on public.api_security_events (scope, client_key_hash, created_at desc);

alter table public.api_security_events enable row level security;
revoke all on table public.api_security_events from anon, authenticated;
grant select, insert, delete on table public.api_security_events to service_role;

create table if not exists public.api_usage_events (
    id bigint generated by default as identity primary key,
    scope text not null,
    client_key_hash text not null,
    outcome text not null check (outcome in ('success', 'failure', 'blocked')),
    resource_id text,
    latency_ms integer,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists api_usage_events_scope_created_idx
    on public.api_usage_events (scope, created_at desc);

alter table public.api_usage_events enable row level security;
revoke all on table public.api_usage_events from anon, authenticated;
grant select, insert on table public.api_usage_events to service_role;
grant usage, select on sequence public.api_usage_events_id_seq to service_role;

create or replace function public.psi_consume_api_quota(
    p_scope text,
    p_client_key_hash text,
    p_max_requests integer,
    p_window_seconds integer,
    p_metadata jsonb default '{}'::jsonb
)
returns table(allowed boolean, current_count integer, retry_after_seconds integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_count integer;
    v_oldest timestamptz;
    v_window interval;
begin
    if coalesce(trim(p_scope), '') = ''
       or coalesce(trim(p_client_key_hash), '') = ''
       or p_max_requests < 1
       or p_window_seconds < 1 then
        raise exception 'invalid quota arguments';
    end if;

    perform pg_advisory_xact_lock(hashtext(p_scope || ':' || p_client_key_hash));
    v_window := make_interval(secs => p_window_seconds);

    select count(*)::integer, min(created_at)
      into v_count, v_oldest
      from public.api_security_events
     where scope = p_scope
       and client_key_hash = p_client_key_hash
       and created_at >= now() - v_window;

    if v_count >= p_max_requests then
        return query select false, v_count,
            greatest(1, ceil(extract(epoch from ((v_oldest + v_window) - now())))::integer);
        return;
    end if;

    insert into public.api_security_events(scope, client_key_hash, metadata)
    values (p_scope, p_client_key_hash, coalesce(p_metadata, '{}'::jsonb));

    return query select true, v_count + 1, 0;
end;
$$;

revoke all on function public.psi_consume_api_quota(text, text, integer, integer, jsonb) from public, anon, authenticated;
grant execute on function public.psi_consume_api_quota(text, text, integer, integer, jsonb) to service_role;

create index if not exists workers_phone_normalized_idx
    on public.workers ((regexp_replace(coalesce(phone_number, ''), '\D', '', 'g')));
create index if not exists workers_birth_date_normalized_idx
    on public.workers ((regexp_replace(coalesce(birth_date, ''), '\D', '', 'g')));
create index if not exists workers_passport_normalized_idx
    on public.workers ((upper(regexp_replace(coalesce(passport_number, ''), '[^A-Za-z0-9]', '', 'g'))));

create or replace function public.psi_lookup_worker_auth(p_key_type text, p_key_value text)
returns table(id uuid, name text, nationality text)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select w.id, w.name, w.nationality
      from public.workers w
     where coalesce(to_jsonb(w)->>'deleted_at', '') = ''
       and (
           (p_key_type = 'phone' and regexp_replace(coalesce(w.phone_number, ''), '\D', '', 'g') = regexp_replace(coalesce(p_key_value, ''), '\D', '', 'g'))
        or (p_key_type = 'birthDate' and regexp_replace(coalesce(w.birth_date, ''), '\D', '', 'g') = regexp_replace(coalesce(p_key_value, ''), '\D', '', 'g'))
        or (p_key_type = 'passport' and upper(regexp_replace(coalesce(w.passport_number, ''), '[^A-Za-z0-9]', '', 'g')) = upper(regexp_replace(coalesce(p_key_value, ''), '[^A-Za-z0-9]', '', 'g')))
       )
     order by w.id
     limit 2;
$$;

revoke all on function public.psi_lookup_worker_auth(text, text) from public, anon, authenticated;
grant execute on function public.psi_lookup_worker_auth(text, text) to service_role;

commit;
