export type ReportLanguageCode =
    | 'ko'
    | 'vi'
    | 'zh'
    | 'th'
    | 'my'
    | 'uz'
    | 'km'
    | 'id'
    | 'ms'
    | 'mn'
    | 'ru'
    | 'kk'
    | 'ne'
    | 'en';

export interface ReportLanguageLabels {
    certificateTitle: string;
    monthlyReportTitle: string;
    officialRecord: string;
    workerInfo: string;
    educationDate: string;
    issueDate: string;
    totalScore: string;
    scoreStandard: string;
    advanced: string;
    intermediate: string;
    beginner: string;
    qualityBasis: string;
    noQualityBasis: string;
    metricDetailHint: string;
    coaching: string;
    strengths: string;
    weaknesses: string;
    verdict: string;
    actionChecklist: string;
    trend: string;
    sixMonths: string;
    pictogram: string;
    original: string;
    noImage: string;
    recordCount: string;
    monthCount: string;
    assessmentPeriod: string;
    documentId: string;
    safetyManager: string;
    siteManager: string;
    scopeTitle: string;
    scopeText: string;
    officialFooter: string;
    reassessment: string;
}

export interface ReportLanguagePolicy {
    code: ReportLanguageCode;
    locale: string;
    countryName: string;
    languageNameKo: string;
    fontFamily: string;
    labels: ReportLanguageLabels;
    metrics: [string, string, string, string, string, string];
    genericWork: string;
    genericGuidance: string;
    genericVerdict: string;
    genericCoaching: string;
}

const latinFont = "'Noto Sans', 'Segoe UI', Arial, sans-serif";
const cyrillicFont = "'Noto Sans', 'Segoe UI', Arial, sans-serif";

export const REPORT_LANGUAGE_POLICIES: Record<ReportLanguageCode, ReportLanguagePolicy> = {
    ko: {
        code: 'ko',
        locale: 'ko-KR',
        countryName: '대한민국',
        languageNameKo: '한국어',
        fontFamily: "'Pretendard', 'Noto Sans KR', 'Malgun Gothic', sans-serif",
        labels: {
            certificateTitle: '안전 역량 인증서',
            monthlyReportTitle: '월간 안전보건교육 역량 진단',
            officialRecord: 'PSI 공식 발행',
            workerInfo: '근로자 정보',
            educationDate: '평가일',
            issueDate: '발행일',
            totalScore: '위험인식 신호',
            scoreStandard: '지원단계 기준',
            advanced: '안정',
            intermediate: '확인',
            beginner: '우선지원',
            qualityBasis: '상세 품질 판단 근거',
            noQualityBasis: '품질 판단 근거 없음',
            metricDetailHint: '세부 지표 해설은 관리자 분석 부록에서 확인합니다.',
            coaching: '안전 실천 코칭',
            strengths: '역량 강점',
            weaknesses: '개선 권고',
            verdict: '종합 안전 진단',
            actionChecklist: '현장 실천 체크',
            trend: '안전 추이',
            sixMonths: '최근 6개월',
            pictogram: '필수 안전 표지',
            original: '수기 기록 원본',
            noImage: '이미지 없음',
            recordCount: '평가기록',
            monthCount: '평가개월',
            assessmentPeriod: '평가기간',
            documentId: '발행번호',
            safetyManager: '안전관리자',
            siteManager: '현장관리자',
            scopeTitle: '발행 범위',
            scopeText: '본 인증서는 PSI 안전교육 기록을 바탕으로 한 현장 역량 확인서이며 법정 자격증을 대체하지 않습니다.',
            officialFooter: 'PSI 안전 인텔리전스 시스템 · 안전교육 역량 확인',
            reassessment: '재평가',
        },
        metrics: ['응답 충실도', '업무 이해도', '위험평가 이해', '작업 숙련도', '개선 이행력', '반복위반 감점'],
        genericWork: '건설 작업',
        genericGuidance: '작업 전 위험요인, 보호구, 작업순서를 빠짐없이 확인하고 현장 조건이 바뀌면 즉시 멈춘 뒤 위험을 다시 평가하세요.',
        genericVerdict: '안전 작업을 위해 확인된 주요 위험의 보호조치를 작업 전·중·후에 반복 확인해야 합니다.',
        genericCoaching: '매 작업 전 보호구와 작업구역을 확인하고 교육받은 안전 절차를 끝까지 지켜 주세요.',
    },
    vi: {
        code: 'vi',
        locale: 'vi-VN',
        countryName: 'Việt Nam',
        languageNameKo: '베트남어',
        fontFamily: latinFont,
        labels: {
            certificateTitle: 'Chứng nhận Năng lực An toàn',
            monthlyReportTitle: 'Đánh giá năng lực đào tạo an toàn hằng tháng',
            officialRecord: 'PSI phát hành chính thức',
            workerInfo: 'Thông tin người lao động',
            educationDate: 'Ngày đánh giá',
            issueDate: 'Ngày phát hành',
            totalScore: 'Tín hiệu nhận biết rủi ro',
            scoreStandard: 'Tiêu chuẩn bước hỗ trợ',
            advanced: 'Ổn định',
            intermediate: 'Cần kiểm tra',
            beginner: 'Ưu tiên hỗ trợ',
            qualityBasis: 'Căn cứ đánh giá',
            noQualityBasis: 'Chưa có căn cứ đánh giá chi tiết',
            metricDetailHint: 'Xem phần phân tích dành cho quản lý để biết chi tiết các chỉ số.',
            coaching: 'Hướng dẫn thực hành an toàn',
            strengths: 'Điểm mạnh',
            weaknesses: 'Điểm cần cải thiện',
            verdict: 'Đánh giá an toàn tổng hợp',
            actionChecklist: 'Kiểm tra hành động tại hiện trường',
            trend: 'Xu hướng an toàn',
            sixMonths: '6 tháng gần nhất',
            pictogram: 'Biển báo an toàn thiết yếu',
            original: 'Bản ghi viết tay',
            noImage: 'Không có hình ảnh',
            recordCount: 'Số lần đánh giá',
            monthCount: 'Số tháng đánh giá',
            assessmentPeriod: 'Thời gian đánh giá',
            documentId: 'Mã phát hành',
            safetyManager: 'Quản lý an toàn',
            siteManager: 'Quản lý công trường',
            scopeTitle: 'Phạm vi chứng nhận',
            scopeText: 'Chứng nhận này xác nhận năng lực dựa trên hồ sơ đào tạo an toàn PSI và không thay thế giấy phép nghề nghiệp theo pháp luật.',
            officialFooter: 'Hệ thống thông tin an toàn PSI · Xác nhận năng lực đào tạo',
            reassessment: 'Đánh giá lại',
        },
        metrics: ['Mức độ đầy đủ câu trả lời', 'Hiểu biết công việc', 'Hiểu đánh giá rủi ro', 'Mức độ thành thạo', 'Thực hiện cải thiện', 'Khấu trừ vi phạm lặp lại'],
        genericWork: 'công việc xây dựng',
        genericGuidance: 'Trước khi làm việc, hãy kiểm tra đầy đủ nguy cơ, thiết bị bảo hộ và trình tự công việc. Nếu điều kiện thay đổi, hãy dừng lại và đánh giá rủi ro lại.',
        genericVerdict: 'Cần xác nhận lại các biện pháp bảo vệ đối với nguy cơ chính trước, trong và sau công việc.',
        genericCoaching: 'Trước mỗi ca, hãy kiểm tra thiết bị bảo hộ và khu vực làm việc, đồng thời tuân thủ đầy đủ quy trình an toàn đã được hướng dẫn.',
    },
    zh: {
        code: 'zh',
        locale: 'zh-CN',
        countryName: '中国',
        languageNameKo: '중국어',
        fontFamily: "'Noto Sans SC', 'Microsoft YaHei', 'PingFang SC', sans-serif",
        labels: {
            certificateTitle: '安全能力认证书',
            monthlyReportTitle: '月度安全教育能力评估',
            officialRecord: 'PSI 正式签发',
            workerInfo: '工人信息',
            educationDate: '评估日期',
            issueDate: '签发日期',
            totalScore: '风险认知信号',
            scoreStandard: '支持阶段标准',
            advanced: '稳定',
            intermediate: '需确认',
            beginner: '优先支持',
            qualityBasis: '详细评估依据',
            noQualityBasis: '暂无详细评估依据',
            metricDetailHint: '详细指标请查看管理人员分析附录。',
            coaching: '安全实践指导',
            strengths: '能力优势',
            weaknesses: '改进建议',
            verdict: '综合安全评估',
            actionChecklist: '现场行动检查',
            trend: '安全趋势',
            sixMonths: '最近六个月',
            pictogram: '必要安全标志',
            original: '手写记录原件',
            noImage: '无图像',
            recordCount: '评估记录',
            monthCount: '评估月份',
            assessmentPeriod: '评估期间',
            documentId: '签发编号',
            safetyManager: '安全管理员',
            siteManager: '现场管理员',
            scopeTitle: '认证范围',
            scopeText: '本证书依据 PSI 安全教育记录确认现场能力，不替代法律规定的职业资格证书。',
            officialFooter: 'PSI 安全智能系统 · 安全教育能力确认',
            reassessment: '重新评估',
        },
        metrics: ['回答完整度', '作业理解度', '风险评估理解', '作业熟练度', '改进执行力', '重复违规扣分'],
        genericWork: '施工作业',
        genericGuidance: '作业前请完整确认危险点、防护用品和作业顺序。现场条件发生变化时，应立即停止并重新评估风险。',
        genericVerdict: '必须在作业前、作业中和作业后反复确认主要风险的防护措施。',
        genericCoaching: '每班作业前检查防护用品和作业区域，并严格遵守已培训的安全程序。',
    },
    th: {
        code: 'th',
        locale: 'th-TH',
        countryName: 'ประเทศไทย',
        languageNameKo: '태국어',
        fontFamily: "'Noto Sans Thai', 'Leelawadee UI', Tahoma, sans-serif",
        labels: {
            certificateTitle: 'ใบรับรองสมรรถนะด้านความปลอดภัย',
            monthlyReportTitle: 'การประเมินสมรรถนะการอบรมความปลอดภัยประจำเดือน',
            officialRecord: 'ออกอย่างเป็นทางการโดย PSI',
            workerInfo: 'ข้อมูลผู้ปฏิบัติงาน',
            educationDate: 'วันที่ประเมิน',
            issueDate: 'วันที่ออก',
            totalScore: 'สัญญาณการรับรู้ความเสี่ยง',
            scoreStandard: 'เกณฑ์ขั้นการสนับสนุน',
            advanced: 'มั่นคง',
            intermediate: 'ต้องตรวจสอบ',
            beginner: 'สนับสนุนก่อน',
            qualityBasis: 'หลักฐานการประเมิน',
            noQualityBasis: 'ไม่มีหลักฐานการประเมินโดยละเอียด',
            metricDetailHint: 'ดูรายละเอียดตัวชี้วัดในภาคผนวกสำหรับผู้จัดการ',
            coaching: 'คำแนะนำการปฏิบัติงานอย่างปลอดภัย',
            strengths: 'จุดแข็ง',
            weaknesses: 'ข้อเสนอเพื่อปรับปรุง',
            verdict: 'การประเมินความปลอดภัยโดยรวม',
            actionChecklist: 'รายการตรวจการปฏิบัติหน้างาน',
            trend: 'แนวโน้มความปลอดภัย',
            sixMonths: 'หกเดือนล่าสุด',
            pictogram: 'ป้ายความปลอดภัยที่จำเป็น',
            original: 'บันทึกลายมือเดิม',
            noImage: 'ไม่มีรูปภาพ',
            recordCount: 'จำนวนการประเมิน',
            monthCount: 'จำนวนเดือน',
            assessmentPeriod: 'ช่วงเวลาประเมิน',
            documentId: 'เลขที่ออก',
            safetyManager: 'ผู้จัดการความปลอดภัย',
            siteManager: 'ผู้จัดการหน้างาน',
            scopeTitle: 'ขอบเขตการรับรอง',
            scopeText: 'ใบรับรองนี้ยืนยันสมรรถนะจากบันทึกการอบรมความปลอดภัยของ PSI และไม่ใช้แทนใบอนุญาตวิชาชีพตามกฎหมาย',
            officialFooter: 'ระบบข้อมูลความปลอดภัย PSI · การยืนยันสมรรถนะการอบรม',
            reassessment: 'การประเมินซ้ำ',
        },
        metrics: ['ความครบถ้วนของคำตอบ', 'ความเข้าใจงาน', 'ความเข้าใจการประเมินความเสี่ยง', 'ความชำนาญงาน', 'การดำเนินการปรับปรุง', 'หักคะแนนการทำผิดซ้ำ'],
        genericWork: 'งานก่อสร้าง',
        genericGuidance: 'ก่อนเริ่มงาน ให้ตรวจสอบอันตราย อุปกรณ์ป้องกัน และลำดับงานให้ครบถ้วน หากสภาพหน้างานเปลี่ยน ให้หยุดและประเมินความเสี่ยงใหม่',
        genericVerdict: 'ต้องตรวจสอบมาตรการป้องกันความเสี่ยงหลักซ้ำทั้งก่อน ระหว่าง และหลังการทำงาน',
        genericCoaching: 'ก่อนทุกกะ ให้ตรวจอุปกรณ์ป้องกันและพื้นที่ทำงาน พร้อมปฏิบัติตามขั้นตอนความปลอดภัยที่ได้รับการอบรมอย่างครบถ้วน',
    },
    my: {
        code: 'my',
        locale: 'my-MM',
        countryName: 'မြန်မာ',
        languageNameKo: '미얀마어',
        fontFamily: "'Noto Sans Myanmar', 'Myanmar Text', 'Nirmala UI', sans-serif",
        labels: {
            certificateTitle: 'ဘေးကင်းလုံခြုံရေး စွမ်းရည် လက်မှတ်',
            monthlyReportTitle: 'လစဉ် ဘေးကင်းရေးပညာပေး စွမ်းရည် အကဲဖြတ်ချက်',
            officialRecord: 'PSI တရားဝင် ထုတ်ပေးမှု',
            workerInfo: 'အလုပ်သမား အချက်အလက်',
            educationDate: 'အကဲဖြတ်ရက်',
            issueDate: 'ထုတ်ပေးရက်',
            totalScore: 'အန္တရာယ်သိမြင်မှု အချက်ပြ',
            scoreStandard: 'ပံ့ပိုးမှုအဆင့် သတ်မှတ်ချက်',
            advanced: 'တည်ငြိမ်',
            intermediate: 'စစ်ဆေးရန်',
            beginner: 'ဦးစားပေး ပံ့ပိုး',
            qualityBasis: 'အကဲဖြတ် အထောက်အထား',
            noQualityBasis: 'အသေးစိတ် အကဲဖြတ် အထောက်အထား မရှိပါ',
            metricDetailHint: 'ညွှန်းကိန်းအသေးစိတ်ကို မန်နေဂျာသုံး နောက်ဆက်တွဲတွင် ကြည့်ပါ။',
            coaching: 'ဘေးကင်းရေး လက်တွေ့ လမ်းညွှန်',
            strengths: 'အားသာချက်များ',
            weaknesses: 'တိုးတက်ရန် အချက်များ',
            verdict: 'ဘေးကင်းရေး စုစုပေါင်း သုံးသပ်ချက်',
            actionChecklist: 'လုပ်ငန်းခွင် လုပ်ဆောင်ချက် စစ်ဆေးစာရင်း',
            trend: 'ဘေးကင်းရေး အခြေအနေ',
            sixMonths: 'နောက်ဆုံး ခြောက်လ',
            pictogram: 'မရှိမဖြစ် ဘေးကင်းရေး သင်္ကေတ',
            original: 'မူရင်း လက်ရေးမှတ်တမ်း',
            noImage: 'ပုံ မရှိပါ',
            recordCount: 'အကဲဖြတ် မှတ်တမ်း',
            monthCount: 'အကဲဖြတ် လများ',
            assessmentPeriod: 'အကဲဖြတ် ကာလ',
            documentId: 'ထုတ်ပေး အမှတ်',
            safetyManager: 'ဘေးကင်းရေး မန်နေဂျာ',
            siteManager: 'လုပ်ငန်းခွင် မန်နေဂျာ',
            scopeTitle: 'အသိအမှတ်ပြု နယ်ပယ်',
            scopeText: 'ဤလက်မှတ်သည် PSI ဘေးကင်းရေးပညာပေး မှတ်တမ်းအပေါ် အခြေခံသည့် လုပ်ငန်းခွင်စွမ်းရည် အတည်ပြုချက်ဖြစ်ပြီး ဥပဒေအရ လုပ်ငန်းလိုင်စင်ကို အစားမထိုးပါ။',
            officialFooter: 'PSI ဘေးကင်းရေး အသိဉာဏ်စနစ် · ပညာပေးစွမ်းရည် အတည်ပြုချက်',
            reassessment: 'ပြန်လည်အကဲဖြတ်',
        },
        metrics: ['ဖြေဆိုမှု ပြည့်စုံခြင်း', 'အလုပ် နားလည်မှု', 'အန္တရာယ် အကဲဖြတ် နားလည်မှု', 'အလုပ် ကျွမ်းကျင်မှု', 'တိုးတက်မှု အကောင်အထည်ဖော်ခြင်း', 'ထပ်ခါတလဲလဲ ချိုးဖောက်မှု အမှတ်လျှော့'],
        genericWork: 'ဆောက်လုပ်ရေးအလုပ်',
        genericGuidance: 'အလုပ်မစမီ အန္တရာယ်များ၊ ကိုယ်ကာကွယ်ပစ္စည်းများနှင့် အလုပ်စဉ်ကို အပြည့်အစုံ စစ်ဆေးပါ။ အခြေအနေပြောင်းလဲပါက ရပ်ပြီး အန္တရာယ်ကို ပြန်လည်အကဲဖြတ်ပါ။',
        genericVerdict: 'အဓိကအန္တရာယ်များအတွက် ကာကွယ်ရေးအစီအမံကို အလုပ်မစမီ၊ လုပ်နေစဉ်နှင့် ပြီးနောက် ထပ်မံစစ်ဆေးရမည်။',
        genericCoaching: 'အလုပ်ဆိုင်းတိုင်း မစတင်မီ ကာကွယ်ရေးပစ္စည်းနှင့် လုပ်ငန်းခွင်ကို စစ်ဆေးပြီး သင်ကြားထားသော ဘေးကင်းရေးလုပ်ထုံးလုပ်နည်းကို လိုက်နာပါ။',
    },
    uz: {
        code: 'uz',
        locale: 'uz-UZ',
        countryName: 'Oʻzbekiston',
        languageNameKo: '우즈베크어',
        fontFamily: latinFont,
        labels: {
            certificateTitle: 'Xavfsizlik malakasi sertifikati',
            monthlyReportTitle: 'Oylik xavfsizlik taʼlimi malakasini baholash',
            officialRecord: 'PSI rasmiy nashri',
            workerInfo: 'Ishchi maʼlumotlari',
            educationDate: 'Baholash sanasi',
            issueDate: 'Berilgan sana',
            totalScore: 'Xavfni anglash signali',
            scoreStandard: 'Qoʻllab-quvvatlash bosqichi mezoni',
            advanced: 'Barqaror',
            intermediate: 'Tekshirish',
            beginner: 'Ustuvor yordam',
            qualityBasis: 'Baholash asoslari',
            noQualityBasis: 'Batafsil baholash asosi yoʻq',
            metricDetailHint: 'Koʻrsatkichlar tafsiloti rahbar tahlili ilovasida beriladi.',
            coaching: 'Xavfsiz amaliyot boʻyicha yoʻriqnoma',
            strengths: 'Kuchli tomonlar',
            weaknesses: 'Yaxshilash tavsiyalari',
            verdict: 'Umumiy xavfsizlik bahosi',
            actionChecklist: 'Maydon amaliyoti tekshiruvi',
            trend: 'Xavfsizlik dinamikasi',
            sixMonths: 'Soʻnggi olti oy',
            pictogram: 'Muhim xavfsizlik belgilari',
            original: 'Asl qoʻlyozma',
            noImage: 'Rasm yoʻq',
            recordCount: 'Baholash yozuvlari',
            monthCount: 'Baholangan oylar',
            assessmentPeriod: 'Baholash davri',
            documentId: 'Nashr raqami',
            safetyManager: 'Xavfsizlik rahbari',
            siteManager: 'Maydon rahbari',
            scopeTitle: 'Sertifikat doirasi',
            scopeText: 'Ushbu sertifikat PSI xavfsizlik taʼlimi yozuvlari asosidagi maydon malakasini tasdiqlaydi va qonuniy kasbiy litsenziya oʻrnini bosmaydi.',
            officialFooter: 'PSI xavfsizlik intellekti tizimi · Taʼlim malakasini tasdiqlash',
            reassessment: 'Qayta baholash',
        },
        metrics: ['Javob toʻliqligi', 'Ishni tushunish', 'Xavfni baholashni tushunish', 'Ish mahorati', 'Yaxshilashni bajarish', 'Takroriy buzilish chegirmasi'],
        genericWork: 'qurilish ishi',
        genericGuidance: 'Ishdan oldin xavflar, himoya vositalari va ish ketma-ketligini toʻliq tekshiring. Sharoit oʻzgarsa, toʻxtab xavfni qayta baholang.',
        genericVerdict: 'Asosiy xavflar bo‘yicha himoya choralarini ish oldidan, ish vaqtida va ish tugagach takror tekshirish kerak.',
        genericCoaching: 'Har smenadan oldin himoya vositalari va ish maydonini tekshiring hamda oʻrgatilgan xavfsizlik tartibiga toʻliq rioya qiling.',
    },
    km: {
        code: 'km',
        locale: 'km-KH',
        countryName: 'កម្ពុជា',
        languageNameKo: '크메르어',
        fontFamily: "'Noto Sans Khmer', 'Khmer UI', 'Leelawadee UI', sans-serif",
        labels: {
            certificateTitle: 'វិញ្ញាបនបត្រសមត្ថភាពសុវត្ថិភាព',
            monthlyReportTitle: 'ការវាយតម្លៃសមត្ថភាពអប់រំសុវត្ថិភាពប្រចាំខែ',
            officialRecord: 'ចេញជាផ្លូវការដោយ PSI',
            workerInfo: 'ព័ត៌មានកម្មករ',
            educationDate: 'ថ្ងៃវាយតម្លៃ',
            issueDate: 'ថ្ងៃចេញ',
            totalScore: 'សញ្ញានៃការយល់ដឹងហានិភ័យ',
            scoreStandard: 'លក្ខខណ្ឌដំណាក់កាលគាំទ្រ',
            advanced: 'មានស្ថេរភាព',
            intermediate: 'ត្រូវពិនិត្យ',
            beginner: 'គាំទ្រអាទិភាព',
            qualityBasis: 'មូលដ្ឋានវាយតម្លៃ',
            noQualityBasis: 'មិនមានមូលដ្ឋានវាយតម្លៃលម្អិត',
            metricDetailHint: 'សូមមើលព័ត៌មានលម្អិតក្នុងឯកសារភ្ជាប់សម្រាប់អ្នកគ្រប់គ្រង។',
            coaching: 'ការណែនាំអនុវត្តសុវត្ថិភាព',
            strengths: 'ចំណុចខ្លាំង',
            weaknesses: 'ចំណុចត្រូវកែលម្អ',
            verdict: 'ការវាយតម្លៃសុវត្ថិភាពសរុប',
            actionChecklist: 'បញ្ជីត្រួតពិនិត្យការអនុវត្ត',
            trend: 'និន្នាការសុវត្ថិភាព',
            sixMonths: 'ប្រាំមួយខែចុងក្រោយ',
            pictogram: 'សញ្ញាសុវត្ថិភាពសំខាន់',
            original: 'កំណត់ត្រាសរសេរដើម',
            noImage: 'គ្មានរូបភាព',
            recordCount: 'កំណត់ត្រាវាយតម្លៃ',
            monthCount: 'ខែវាយតម្លៃ',
            assessmentPeriod: 'រយៈពេលវាយតម្លៃ',
            documentId: 'លេខចេញ',
            safetyManager: 'អ្នកគ្រប់គ្រងសុវត្ថិភាព',
            siteManager: 'អ្នកគ្រប់គ្រងការដ្ឋាន',
            scopeTitle: 'វិសាលភាពវិញ្ញាបនបត្រ',
            scopeText: 'វិញ្ញាបនបត្រនេះបញ្ជាក់សមត្ថភាពតាមកំណត់ត្រាអប់រំសុវត្ថិភាព PSI ហើយមិនជំនួសអាជ្ញាបណ្ណវិជ្ជាជីវៈតាមច្បាប់ទេ។',
            officialFooter: 'ប្រព័ន្ធបញ្ញាសុវត្ថិភាព PSI · ការបញ្ជាក់សមត្ថភាពអប់រំ',
            reassessment: 'វាយតម្លៃឡើងវិញ',
        },
        metrics: ['ភាពពេញលេញនៃចម្លើយ', 'ការយល់ដឹងអំពីការងារ', 'ការយល់ដឹងអំពីហានិភ័យ', 'ជំនាញការងារ', 'ការអនុវត្តការកែលម្អ', 'កាត់ពិន្ទុការរំលោភដដែល'],
        genericWork: 'ការងារសំណង់',
        genericGuidance: 'មុនចាប់ផ្តើមការងារ សូមពិនិត្យហានិភ័យ ឧបករណ៍ការពារ និងលំដាប់ការងារឱ្យបានពេញលេញ។ បើលក្ខខណ្ឌផ្លាស់ប្តូរ សូមឈប់ និងវាយតម្លៃហានិភ័យឡើងវិញ។',
        genericVerdict: 'ត្រូវពិនិត្យវិធានការការពារហានិភ័យសំខាន់ម្តងទៀត មុន ពេល និងក្រោយការងារ។',
        genericCoaching: 'មុនគ្រប់វេន សូមពិនិត្យឧបករណ៍ការពារ និងតំបន់ការងារ ហើយអនុវត្តតាមនីតិវិធីសុវត្ថិភាពដែលបានបណ្តុះបណ្តាល។',
    },
    id: {
        code: 'id',
        locale: 'id-ID',
        countryName: 'Indonesia',
        languageNameKo: '인도네시아어',
        fontFamily: latinFont,
        labels: {
            certificateTitle: 'Sertifikat Kompetensi Keselamatan',
            monthlyReportTitle: 'Penilaian kompetensi pelatihan keselamatan bulanan',
            officialRecord: 'Diterbitkan resmi oleh PSI',
            workerInfo: 'Informasi pekerja',
            educationDate: 'Tanggal penilaian',
            issueDate: 'Tanggal terbit',
            totalScore: 'Sinyal kesadaran risiko',
            scoreStandard: 'Standar tahap dukungan',
            advanced: 'Stabil',
            intermediate: 'Perlu cek',
            beginner: 'Prioritas dukungan',
            qualityBasis: 'Dasar penilaian',
            noQualityBasis: 'Belum ada dasar penilaian rinci',
            metricDetailHint: 'Lihat lampiran analisis pengelola untuk rincian indikator.',
            coaching: 'Panduan praktik keselamatan',
            strengths: 'Kekuatan',
            weaknesses: 'Saran perbaikan',
            verdict: 'Penilaian keselamatan menyeluruh',
            actionChecklist: 'Pemeriksaan tindakan lapangan',
            trend: 'Tren keselamatan',
            sixMonths: 'Enam bulan terakhir',
            pictogram: 'Rambu keselamatan penting',
            original: 'Catatan tulisan tangan asli',
            noImage: 'Tidak ada gambar',
            recordCount: 'Catatan penilaian',
            monthCount: 'Bulan penilaian',
            assessmentPeriod: 'Periode penilaian',
            documentId: 'Nomor terbit',
            safetyManager: 'Manajer keselamatan',
            siteManager: 'Manajer lapangan',
            scopeTitle: 'Ruang lingkup sertifikat',
            scopeText: 'Sertifikat ini mengonfirmasi kompetensi berdasarkan catatan pelatihan keselamatan PSI dan tidak menggantikan lisensi profesi yang diwajibkan hukum.',
            officialFooter: 'Sistem Intelijen Keselamatan PSI · Konfirmasi kompetensi pelatihan',
            reassessment: 'Penilaian ulang',
        },
        metrics: ['Kelengkapan jawaban', 'Pemahaman pekerjaan', 'Pemahaman penilaian risiko', 'Kemahiran kerja', 'Pelaksanaan perbaikan', 'Pengurangan pelanggaran berulang'],
        genericWork: 'pekerjaan konstruksi',
        genericGuidance: 'Sebelum bekerja, periksa bahaya, APD, dan urutan kerja secara lengkap. Jika kondisi berubah, berhenti dan lakukan penilaian risiko ulang.',
        genericVerdict: 'Tindakan perlindungan untuk risiko utama harus diperiksa kembali sebelum, selama, dan setelah pekerjaan.',
        genericCoaching: 'Sebelum setiap giliran kerja, periksa APD dan area kerja serta patuhi seluruh prosedur keselamatan yang telah dilatihkan.',
    },
    ms: {
        code: 'ms',
        locale: 'ms-MY',
        countryName: 'Malaysia',
        languageNameKo: '말레이어',
        fontFamily: latinFont,
        labels: {
            certificateTitle: 'Sijil Kompetensi Keselamatan',
            monthlyReportTitle: 'Penilaian kompetensi latihan keselamatan bulanan',
            officialRecord: 'Dikeluarkan secara rasmi oleh PSI',
            workerInfo: 'Maklumat pekerja',
            educationDate: 'Tarikh penilaian',
            issueDate: 'Tarikh dikeluarkan',
            totalScore: 'Isyarat kesedaran risiko',
            scoreStandard: 'Piawaian tahap sokongan',
            advanced: 'Stabil',
            intermediate: 'Perlu semak',
            beginner: 'Sokongan utama',
            qualityBasis: 'Asas penilaian',
            noQualityBasis: 'Tiada asas penilaian terperinci',
            metricDetailHint: 'Lihat lampiran analisis pengurus untuk butiran petunjuk.',
            coaching: 'Panduan amalan keselamatan',
            strengths: 'Kekuatan',
            weaknesses: 'Cadangan penambahbaikan',
            verdict: 'Penilaian keselamatan menyeluruh',
            actionChecklist: 'Semakan tindakan tapak',
            trend: 'Trend keselamatan',
            sixMonths: 'Enam bulan terkini',
            pictogram: 'Tanda keselamatan penting',
            original: 'Rekod tulisan tangan asal',
            noImage: 'Tiada imej',
            recordCount: 'Rekod penilaian',
            monthCount: 'Bulan penilaian',
            assessmentPeriod: 'Tempoh penilaian',
            documentId: 'Nombor keluaran',
            safetyManager: 'Pengurus keselamatan',
            siteManager: 'Pengurus tapak',
            scopeTitle: 'Skop sijil',
            scopeText: 'Sijil ini mengesahkan kompetensi berdasarkan rekod latihan keselamatan PSI dan tidak menggantikan lesen profesional yang diwajibkan undang-undang.',
            officialFooter: 'Sistem Perisikan Keselamatan PSI · Pengesahan kompetensi latihan',
            reassessment: 'Penilaian semula',
        },
        metrics: ['Kelengkapan jawapan', 'Pemahaman kerja', 'Pemahaman penilaian risiko', 'Kemahiran kerja', 'Pelaksanaan penambahbaikan', 'Potongan pelanggaran berulang'],
        genericWork: 'kerja pembinaan',
        genericGuidance: 'Sebelum bekerja, periksa bahaya, peralatan perlindungan dan urutan kerja sepenuhnya. Jika keadaan berubah, berhenti dan nilai semula risiko.',
        genericVerdict: 'Langkah perlindungan bagi risiko utama perlu disemak sebelum, semasa dan selepas kerja.',
        genericCoaching: 'Sebelum setiap syif, periksa peralatan perlindungan dan kawasan kerja serta patuhi semua prosedur keselamatan yang telah diajar.',
    },
    mn: {
        code: 'mn',
        locale: 'mn-MN',
        countryName: 'Монгол',
        languageNameKo: '몽골어',
        fontFamily: cyrillicFont,
        labels: {
            certificateTitle: 'Аюулгүй ажиллагааны чадамжийн гэрчилгээ',
            monthlyReportTitle: 'Сарын аюулгүй ажиллагааны сургалтын чадамжийн үнэлгээ',
            officialRecord: 'PSI албан ёсны олголт',
            workerInfo: 'Ажилтны мэдээлэл',
            educationDate: 'Үнэлгээний огноо',
            issueDate: 'Олгосон огноо',
            totalScore: 'Эрсдэлийн ойлголтын дохио',
            scoreStandard: 'Дэмжлэгийн шатны шалгуур',
            advanced: 'Тогтвортой',
            intermediate: 'Шалгах',
            beginner: 'Тэргүүн дэмжлэг',
            qualityBasis: 'Үнэлгээний үндэслэл',
            noQualityBasis: 'Дэлгэрэнгүй үнэлгээний үндэслэл алга',
            metricDetailHint: 'Үзүүлэлтийн дэлгэрэнгүйг менежерийн шинжилгээний хавсралтаас үзнэ үү.',
            coaching: 'Аюулгүй ажиллагааны зөвлөмж',
            strengths: 'Давуу тал',
            weaknesses: 'Сайжруулах зөвлөмж',
            verdict: 'Аюулгүй байдлын нэгдсэн үнэлгээ',
            actionChecklist: 'Талбайн үйлдлийн шалгалт',
            trend: 'Аюулгүй байдлын хандлага',
            sixMonths: 'Сүүлийн зургаан сар',
            pictogram: 'Зайлшгүй аюулгүй байдлын тэмдэг',
            original: 'Гар бичмэлийн эх',
            noImage: 'Зураг алга',
            recordCount: 'Үнэлгээний бүртгэл',
            monthCount: 'Үнэлсэн сар',
            assessmentPeriod: 'Үнэлгээний хугацаа',
            documentId: 'Олголтын дугаар',
            safetyManager: 'Аюулгүй байдлын менежер',
            siteManager: 'Талбайн менежер',
            scopeTitle: 'Гэрчилгээний хамрах хүрээ',
            scopeText: 'Энэхүү гэрчилгээ нь PSI аюулгүй ажиллагааны сургалтын бүртгэлд тулгуурласан талбайн чадамжийг баталгаажуулах бөгөөд хууль ёсны мэргэжлийн үнэмлэхийг орлохгүй.',
            officialFooter: 'PSI аюулгүй байдлын ухаалаг систем · Сургалтын чадамжийн баталгаа',
            reassessment: 'Дахин үнэлгээ',
        },
        metrics: ['Хариултын бүрэн байдал', 'Ажлын ойлголт', 'Эрсдэлийн үнэлгээний ойлголт', 'Ажлын ур чадвар', 'Сайжруулалт хэрэгжүүлэх чадвар', 'Давтан зөрчлийн хасалт'],
        genericWork: 'барилгын ажил',
        genericGuidance: 'Ажил эхлэхээс өмнө аюул, хамгаалах хэрэгсэл, ажлын дарааллыг бүрэн шалгана уу. Нөхцөл өөрчлөгдвөл зогсож эрсдэлийг дахин үнэлнэ үү.',
        genericVerdict: 'Гол эрсдэлийн хамгаалалтын арга хэмжээг ажлын өмнө, явцад болон дараа дахин шалгах шаардлагатай.',
        genericCoaching: 'Ээлж бүрийн өмнө хамгаалах хэрэгсэл болон ажлын талбайг шалгаж, заасан аюулгүй ажиллагааны журмыг бүрэн мөрдөнө үү.',
    },
    ru: {
        code: 'ru',
        locale: 'ru-RU',
        countryName: 'Россия',
        languageNameKo: '러시아어',
        fontFamily: cyrillicFont,
        labels: {
            certificateTitle: 'Сертификат компетенции по безопасности',
            monthlyReportTitle: 'Ежемесячная оценка обучения охране труда',
            officialRecord: 'Официально выдано PSI',
            workerInfo: 'Информация о работнике',
            educationDate: 'Дата оценки',
            issueDate: 'Дата выдачи',
            totalScore: 'Сигнал понимания риска',
            scoreStandard: 'Критерий этапа поддержки',
            advanced: 'Стабильно',
            intermediate: 'Проверить',
            beginner: 'Приоритетная поддержка',
            qualityBasis: 'Основания оценки',
            noQualityBasis: 'Подробные основания оценки отсутствуют',
            metricDetailHint: 'Подробные показатели приведены в приложении для руководителя.',
            coaching: 'Практические рекомендации по безопасности',
            strengths: 'Сильные стороны',
            weaknesses: 'Рекомендации по улучшению',
            verdict: 'Комплексная оценка безопасности',
            actionChecklist: 'Проверка действий на площадке',
            trend: 'Динамика безопасности',
            sixMonths: 'Последние шесть месяцев',
            pictogram: 'Обязательные знаки безопасности',
            original: 'Оригинал рукописной записи',
            noImage: 'Изображение отсутствует',
            recordCount: 'Записи оценки',
            monthCount: 'Месяцы оценки',
            assessmentPeriod: 'Период оценки',
            documentId: 'Номер выдачи',
            safetyManager: 'Менеджер по безопасности',
            siteManager: 'Руководитель площадки',
            scopeTitle: 'Область сертификата',
            scopeText: 'Сертификат подтверждает компетенцию на основе записей обучения PSI и не заменяет обязательную профессиональную лицензию.',
            officialFooter: 'Интеллектуальная система безопасности PSI · Подтверждение учебной компетенции',
            reassessment: 'Повторная оценка',
        },
        metrics: ['Полнота ответа', 'Понимание работы', 'Понимание оценки рисков', 'Профессиональные навыки', 'Выполнение улучшений', 'Вычет за повторные нарушения'],
        genericWork: 'строительные работы',
        genericGuidance: 'Перед работой полностью проверьте опасности, средства защиты и порядок операций. При изменении условий остановитесь и повторно оцените риск.',
        genericVerdict: 'Меры защиты от основных рисков необходимо повторно проверять до, во время и после работы.',
        genericCoaching: 'Перед каждой сменой проверяйте средства защиты и рабочую зону, строго соблюдая все изученные процедуры безопасности.',
    },
    kk: {
        code: 'kk',
        locale: 'kk-KZ',
        countryName: 'Қазақстан',
        languageNameKo: '카자흐어',
        fontFamily: cyrillicFont,
        labels: {
            certificateTitle: 'Қауіпсіздік құзыреті сертификаты',
            monthlyReportTitle: 'Ай сайынғы қауіпсіздік оқыту құзыретін бағалау',
            officialRecord: 'PSI ресми түрде берді',
            workerInfo: 'Жұмысшы туралы ақпарат',
            educationDate: 'Бағалау күні',
            issueDate: 'Берілген күні',
            totalScore: 'Қауіпті түсіну сигналы',
            scoreStandard: 'Қолдау кезеңі өлшемі',
            advanced: 'Тұрақты',
            intermediate: 'Тексеру',
            beginner: 'Басым қолдау',
            qualityBasis: 'Бағалау негіздері',
            noQualityBasis: 'Толық бағалау негізі жоқ',
            metricDetailHint: 'Көрсеткіштер туралы толық мәлімет менеджер қосымшасында берілген.',
            coaching: 'Қауіпсіз жұмыс жөніндегі нұсқау',
            strengths: 'Күшті жақтар',
            weaknesses: 'Жақсарту ұсыныстары',
            verdict: 'Жалпы қауіпсіздік бағасы',
            actionChecklist: 'Алаңдағы әрекет тексерісі',
            trend: 'Қауіпсіздік үрдісі',
            sixMonths: 'Соңғы алты ай',
            pictogram: 'Маңызды қауіпсіздік белгілері',
            original: 'Қолжазба түпнұсқасы',
            noImage: 'Сурет жоқ',
            recordCount: 'Бағалау жазбалары',
            monthCount: 'Бағалау айлары',
            assessmentPeriod: 'Бағалау кезеңі',
            documentId: 'Берілім нөмірі',
            safetyManager: 'Қауіпсіздік менеджері',
            siteManager: 'Алаң менеджері',
            scopeTitle: 'Сертификат аясы',
            scopeText: 'Бұл сертификат PSI қауіпсіздік оқыту жазбалары негізіндегі алаң құзыретін растайды және заңды кәсіби лицензияны алмастырмайды.',
            officialFooter: 'PSI қауіпсіздік интеллект жүйесі · Оқыту құзыретін растау',
            reassessment: 'Қайта бағалау',
        },
        metrics: ['Жауап толықтығы', 'Жұмысты түсіну', 'Тәуекелді бағалауды түсіну', 'Жұмыс шеберлігі', 'Жақсартуды орындау', 'Қайталанған бұзушылық шегерімі'],
        genericWork: 'құрылыс жұмысы',
        genericGuidance: 'Жұмыс алдында қауіптерді, қорғаныс құралдарын және жұмыс ретін толық тексеріңіз. Жағдай өзгерсе, тоқтап тәуекелді қайта бағалаңыз.',
        genericVerdict: 'Негізгі қауіптердің қорғаныс шараларын жұмыс алдында, кезінде және соңында қайта тексеру қажет.',
        genericCoaching: 'Әр ауысым алдында қорғаныс құралдары мен жұмыс аймағын тексеріп, үйретілген қауіпсіздік рәсімдерін толық сақтаңыз.',
    },
    ne: {
        code: 'ne',
        locale: 'ne-NP',
        countryName: 'नेपाल',
        languageNameKo: '네팔어',
        fontFamily: "'Noto Sans Devanagari', 'Nirmala UI', Mangal, sans-serif",
        labels: {
            certificateTitle: 'सुरक्षा क्षमता प्रमाणपत्र',
            monthlyReportTitle: 'मासिक सुरक्षा तालिम क्षमता मूल्याङ्कन',
            officialRecord: 'PSI द्वारा आधिकारिक रूपमा जारी',
            workerInfo: 'कामदारको जानकारी',
            educationDate: 'मूल्याङ्कन मिति',
            issueDate: 'जारी मिति',
            totalScore: 'जोखिम बुझाइ संकेत',
            scoreStandard: 'सहयोग चरण मापदण्ड',
            advanced: 'स्थिर',
            intermediate: 'जाँच',
            beginner: 'प्राथमिक सहयोग',
            qualityBasis: 'मूल्याङ्कनको आधार',
            noQualityBasis: 'विस्तृत मूल्याङ्कन आधार उपलब्ध छैन',
            metricDetailHint: 'सूचकको विवरण व्यवस्थापक विश्लेषण परिशिष्टमा हेर्नुहोस्।',
            coaching: 'सुरक्षित अभ्यास निर्देशन',
            strengths: 'सबलीकरण क्षेत्र',
            weaknesses: 'सुधार सुझाव',
            verdict: 'समग्र सुरक्षा मूल्याङ्कन',
            actionChecklist: 'कार्यस्थल कार्य जाँच',
            trend: 'सुरक्षा प्रवृत्ति',
            sixMonths: 'पछिल्ला छ महिना',
            pictogram: 'आवश्यक सुरक्षा सङ्केत',
            original: 'मूल हस्तलिखित अभिलेख',
            noImage: 'तस्बिर उपलब्ध छैन',
            recordCount: 'मूल्याङ्कन अभिलेख',
            monthCount: 'मूल्याङ्कन महिना',
            assessmentPeriod: 'मूल्याङ्कन अवधि',
            documentId: 'जारी नम्बर',
            safetyManager: 'सुरक्षा व्यवस्थापक',
            siteManager: 'साइट व्यवस्थापक',
            scopeTitle: 'प्रमाणपत्रको दायरा',
            scopeText: 'यो प्रमाणपत्र PSI सुरक्षा तालिम अभिलेखमा आधारित कार्यस्थल क्षमता पुष्टि हो र कानुनी पेशागत अनुमतिपत्रको विकल्प होइन।',
            officialFooter: 'PSI सुरक्षा बुद्धिमत्ता प्रणाली · तालिम क्षमता पुष्टि',
            reassessment: 'पुनर्मूल्याङ्कन',
        },
        metrics: ['उत्तरको पूर्णता', 'कामको बुझाइ', 'जोखिम मूल्याङ्कन बुझाइ', 'कामको दक्षता', 'सुधार कार्यान्वयन', 'दोहोरिएको उल्लङ्घन कटौती'],
        genericWork: 'निर्माण कार्य',
        genericGuidance: 'काम सुरु गर्नु अघि जोखिम, सुरक्षा उपकरण र कामको क्रम पूर्ण रूपमा जाँच गर्नुहोस्। अवस्था बदलिएमा रोक्नुहोस् र जोखिम पुनः मूल्याङ्कन गर्नुहोस्।',
        genericVerdict: 'मुख्य जोखिमका सुरक्षा उपाय काम अघि, कामको क्रममा र कामपछि फेरि जाँच गर्नुपर्छ।',
        genericCoaching: 'हरेक सिफ्ट अघि सुरक्षा उपकरण र कार्यक्षेत्र जाँच गरी सिकाइएका सबै सुरक्षा प्रक्रिया पालना गर्नुहोस्।',
    },
    en: {
        code: 'en',
        locale: 'en-US',
        countryName: 'International',
        languageNameKo: '영어',
        fontFamily: latinFont,
        labels: {
            certificateTitle: 'Safety Competency Certificate',
            monthlyReportTitle: 'Monthly Safety Training Competency Assessment',
            officialRecord: 'Officially issued by PSI',
            workerInfo: 'Worker information',
            educationDate: 'Assessment date',
            issueDate: 'Issue date',
            totalScore: 'Risk awareness signal',
            scoreStandard: 'Support stage standard',
            advanced: 'Stable',
            intermediate: 'Check',
            beginner: 'Priority support',
            qualityBasis: 'Assessment basis',
            noQualityBasis: 'No detailed assessment basis available',
            metricDetailHint: 'See the manager analysis appendix for detailed indicators.',
            coaching: 'Safety practice coaching',
            strengths: 'Strengths',
            weaknesses: 'Improvement recommendations',
            verdict: 'Overall safety assessment',
            actionChecklist: 'Site action checklist',
            trend: 'Safety trend',
            sixMonths: 'Latest six months',
            pictogram: 'Essential safety signs',
            original: 'Original handwritten record',
            noImage: 'No image',
            recordCount: 'Assessment records',
            monthCount: 'Assessment months',
            assessmentPeriod: 'Assessment period',
            documentId: 'Document ID',
            safetyManager: 'Safety manager',
            siteManager: 'Site manager',
            scopeTitle: 'Certificate scope',
            scopeText: 'This certificate confirms site competency based on PSI safety training records and does not replace a legally required professional license.',
            officialFooter: 'PSI Safety Intelligence System · Training competency confirmation',
            reassessment: 'Reassessment',
        },
        metrics: ['Response completeness', 'Job understanding', 'Risk assessment understanding', 'Work proficiency', 'Improvement execution', 'Repeat violation deduction'],
        genericWork: 'construction work',
        genericGuidance: 'Before work, fully check hazards, protective equipment, and the work sequence. If conditions change, stop and reassess the risk.',
        genericVerdict: 'Protective measures for the main risks must be checked before, during, and after work.',
        genericCoaching: 'Before every shift, check protective equipment and the work area, and follow all trained safety procedures.',
    },
};

const normalized = (value: unknown): string => String(value || '').trim().toLowerCase();

export const resolveReportLanguageCode = (nationality: string, language?: string): ReportLanguageCode => {
    const nation = normalized(nationality);
    const lang = normalized(language);

    if (nation.includes('대한민국') || nation.includes('한국') || nation.includes('korea') || lang.startsWith('ko')) return 'ko';
    if (nation.includes('베트남') || nation.includes('vietnam') || nation.includes('việt') || lang.startsWith('vi')) return 'vi';
    if (nation.includes('중국') || nation.includes('china') || nation.includes('中国') || lang.startsWith('zh') || lang.startsWith('cmn')) return 'zh';
    if (nation.includes('태국') || nation.includes('thailand') || lang.startsWith('th')) return 'th';
    if (nation.includes('미얀마') || nation.includes('myanmar') || nation.includes('burma') || nation.includes('မြန်မာ') || lang.startsWith('my')) return 'my';
    if (nation.includes('우즈벡') || nation.includes('uzbek') || nation.includes('ўзбек') || nation.includes('узбек') || lang.startsWith('uz')) return 'uz';
    if (nation.includes('캄보디아') || nation.includes('cambodia') || nation.includes('កម្ពុជា') || lang.startsWith('km')) return 'km';
    if (nation.includes('인도네시아') || nation.includes('indonesia') || lang.startsWith('id')) return 'id';
    if (nation.includes('말레이시아') || nation.includes('malaysia') || nation.includes('malay') || lang.startsWith('ms')) return 'ms';
    if (nation.includes('몽골') || nation.includes('mongolia') || nation.includes('монгол') || lang.startsWith('mn')) return 'mn';
    if (nation.includes('러시아') || nation.includes('russia') || nation.includes('росси') || nation.includes('русск') || lang.startsWith('ru')) return 'ru';
    if (nation.includes('카자흐') || nation.includes('kazakhstan') || nation.includes('қазақ') || nation.includes('казах') || lang.startsWith('kk')) return 'kk';
    if (nation.includes('네팔') || nation.includes('nepal') || lang.startsWith('ne')) return 'ne';
    return 'en';
};

export const getReportLanguagePolicy = (nationality: string, language?: string): ReportLanguagePolicy => (
    REPORT_LANGUAGE_POLICIES[resolveReportLanguageCode(nationality, language)]
);

const jobKeys: Record<string, string> = {
    형틀: 'formwork',
    철근: 'rebar',
    골조: 'structure',
    배관: 'piping',
    전기: 'electrical',
    미장: 'plastering',
    비계: 'scaffolding',
    용접: 'welding',
    타설: 'concrete',
    해체: 'demolition',
};

const nativeJobLabels: Record<ReportLanguageCode, Record<string, string>> = {
    ko: { formwork: '형틀', rebar: '철근', structure: '골조', piping: '배관', electrical: '전기', plastering: '미장', scaffolding: '비계', welding: '용접', concrete: '콘크리트 타설', demolition: '해체' },
    vi: { formwork: 'cốp pha', rebar: 'cốt thép', structure: 'kết cấu', piping: 'đường ống', electrical: 'điện', plastering: 'trát', scaffolding: 'giàn giáo', welding: 'hàn', concrete: 'đổ bê tông', demolition: 'tháo dỡ' },
    zh: { formwork: '模板', rebar: '钢筋', structure: '主体结构', piping: '管道', electrical: '电气', plastering: '抹灰', scaffolding: '脚手架', welding: '焊接', concrete: '混凝土浇筑', demolition: '拆除' },
    th: { formwork: 'งานแบบหล่อ', rebar: 'งานเหล็กเสริม', structure: 'งานโครงสร้าง', piping: 'งานท่อ', electrical: 'งานไฟฟ้า', plastering: 'งานฉาบ', scaffolding: 'งานนั่งร้าน', welding: 'งานเชื่อม', concrete: 'งานเทคอนกรีต', demolition: 'งานรื้อถอน' },
    my: { formwork: 'ပုံစံခွက်အလုပ်', rebar: 'သံချောင်းအလုပ်', structure: 'တည်ဆောက်ပုံအလုပ်', piping: 'ပိုက်လိုင်းအလုပ်', electrical: 'လျှပ်စစ်အလုပ်', plastering: 'အင်္ဂတေအလုပ်', scaffolding: 'ငြမ်းအလုပ်', welding: 'ဂဟေဆော်အလုပ်', concrete: 'ကွန်ကရစ်လောင်းခြင်း', demolition: 'ဖြိုဖျက်ခြင်း' },
    uz: { formwork: 'qolip ishi', rebar: 'armatura ishi', structure: 'karkas ishi', piping: 'quvur ishi', electrical: 'elektr ishi', plastering: 'suvoq ishi', scaffolding: 'iskala ishi', welding: 'payvandlash', concrete: 'beton quyish', demolition: 'buzish' },
    km: { formwork: 'ការងារពុម្ព', rebar: 'ការងារដែកសរសៃ', structure: 'ការងារគ្រោង', piping: 'ការងារបំពង់', electrical: 'ការងារអគ្គិសនី', plastering: 'ការងារបូក', scaffolding: 'ការងាររន្ទា', welding: 'ការងារផ្សារ', concrete: 'ការចាក់បេតុង', demolition: 'ការរុះរើ' },
    id: { formwork: 'bekisting', rebar: 'tulangan', structure: 'struktur', piping: 'perpipaan', electrical: 'kelistrikan', plastering: 'plester', scaffolding: 'perancah', welding: 'pengelasan', concrete: 'pengecoran beton', demolition: 'pembongkaran' },
    ms: { formwork: 'acuan', rebar: 'tetulang', structure: 'struktur', piping: 'paip', electrical: 'elektrik', plastering: 'plaster', scaffolding: 'perancah', welding: 'kimpalan', concrete: 'tuangan konkrit', demolition: 'perobohan' },
    mn: { formwork: 'хэв хашмал', rebar: 'арматур', structure: 'каркас', piping: 'шугам хоолой', electrical: 'цахилгаан', plastering: 'шавардлага', scaffolding: 'шат угсралт', welding: 'гагнуур', concrete: 'бетон цутгалт', demolition: 'буулгалт' },
    ru: { formwork: 'опалубочные работы', rebar: 'арматурные работы', structure: 'каркасные работы', piping: 'трубопроводные работы', electrical: 'электромонтажные работы', plastering: 'штукатурные работы', scaffolding: 'работы на лесах', welding: 'сварочные работы', concrete: 'бетонирование', demolition: 'демонтаж' },
    kk: { formwork: 'қалып жұмысы', rebar: 'арматура жұмысы', structure: 'қаңқа жұмысы', piping: 'құбыр жұмысы', electrical: 'электр жұмысы', plastering: 'сылау жұмысы', scaffolding: 'саты жұмысы', welding: 'дәнекерлеу', concrete: 'бетон құю', demolition: 'бөлшектеу' },
    ne: { formwork: 'फर्मवर्क', rebar: 'डन्डी बाँध्ने काम', structure: 'संरचना काम', piping: 'पाइप काम', electrical: 'विद्युतीय काम', plastering: 'प्लास्टर काम', scaffolding: 'मचान काम', welding: 'वेल्डिङ', concrete: 'कङ्क्रिट ढलान', demolition: 'भत्काउने काम' },
    en: { formwork: 'formwork', rebar: 'rebar', structure: 'structural work', piping: 'piping', electrical: 'electrical work', plastering: 'plastering', scaffolding: 'scaffolding', welding: 'welding', concrete: 'concrete placement', demolition: 'demolition' },
};

export const getNativeJobFieldLabel = (jobField: string, policy: ReportLanguagePolicy): string => {
    const source = String(jobField || '').trim();
    const matchedKey = Object.entries(jobKeys).find(([key]) => source.includes(key))?.[1];
    return matchedKey ? nativeJobLabels[policy.code][matchedKey] || policy.genericWork : policy.genericWork;
};

export const getNativeSafetyLevelLabel = (
    safetyLevel: string,
    policy: ReportLanguagePolicy,
): string => {
    if (safetyLevel === '고급') return policy.labels.advanced;
    if (safetyLevel === '중급') return policy.labels.intermediate;
    return policy.labels.beginner;
};

export const hasHangul = (value: string): boolean => /[가-힣]/u.test(String(value || ''));

export const isNativeReportTextClean = (value: string, policy: ReportLanguagePolicy): boolean => {
    const text = String(value || '').trim();
    if (!text) return false;
    if (policy.code !== 'ko' && hasHangul(text)) return false;
    return true;
};
