import React, { useMemo, useState } from 'react';
import type { WorkerRecord } from '../types';
interface Props { workerRecords: WorkerRecord[]; }
const getNextMonth = () => { const date = new Date(); date.setMonth(date.getMonth() + 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; };
const A4EducationMaterial: React.FC<Props> = ({ workerRecords }) => {
    const [educationMonth, setEducationMonth] = useState(getNextMonth); const [workType, setWorkType] = useState('전체 공종'); const [action, setAction] = useState('작업 전 위험요소와 안전조치를 작업자 전원이 함께 확인한다.');
    const workTypes = useMemo(() => ['전체 공종', ...Array.from(new Set(workerRecords.map((item) => item.jobField).filter(Boolean))).sort()], [workerRecords]);
    const targetRecords = useMemo(() => workType === '전체 공종' ? workerRecords : workerRecords.filter((item) => item.jobField === workType), [workerRecords, workType]);
    const risks = useMemo(() => { const counts = new Map<string, number>(); targetRecords.forEach((item) => (item.weakAreas || []).forEach((risk) => counts.set(risk, (counts.get(risk) || 0) + 1))); return [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 4); }, [targetRecords]);
    return <div className="space-y-5 pb-16"><style>{`@media print{.a4-controls{display:none!important}.a4-sheet{box-shadow:none!important;border:0!important}}`}</style>
        <section className="a4-controls rounded-3xl bg-gradient-to-br from-orange-500 to-amber-500 p-6 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[0.16em]">Next Month Preparation</p><h2 className="mt-2 text-2xl font-black">A4 교육자료 자동생성</h2><p className="mt-2 text-sm font-semibold text-orange-50">다음 달 위험성평가 작성 전에 사용하는 도움자료입니다. 개인 점수는 포함하지 않습니다.</p></section>
        <section className="a4-controls grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-3"><label className="text-sm font-black">교육 대상월<input type="month" value={educationMonth} onChange={(event) => setEducationMonth(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3" /></label><label className="text-sm font-black">대상 공종<select value={workType} onChange={(event) => setWorkType(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3">{workTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm font-black">이번 달 실천행동<input value={action} onChange={(event) => setAction(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3" /></label></section>
        <article className="a4-sheet mx-auto min-h-[297mm] w-full max-w-[210mm] rounded-2xl border border-slate-200 bg-white p-8 shadow-xl"><header className="border-b-4 border-orange-500 pb-5"><p className="text-sm font-black text-orange-600">PSI 다음 달 위험교육 도움자료</p><h1 className="mt-2 text-3xl font-black">{educationMonth} {workType} 작업 전 안전확인</h1><p className="mt-2 text-sm font-semibold text-slate-500">다음 달 예정 위험작업 또는 본인 작업을 기준으로 수기 기록을 작성하기 전에 확인합니다.</p></header><section className="mt-7 grid gap-4 sm:grid-cols-2">{risks.length ? risks.map(([risk, count], index) => <div key={risk} className="rounded-2xl border border-orange-100 bg-orange-50 p-5"><span className="text-xs font-black text-orange-600">주요 위험 {index + 1} · 지난 기록 {count}건</span><h2 className="mt-2 text-xl font-black">{risk}</h2><p className="mt-2 text-sm font-semibold text-slate-600">발생 위치와 작업 순서를 확인하고 제거, 차단, 보호구 순서로 대책을 작성합니다.</p></div>) : <div className="sm:col-span-2 rounded-2xl bg-slate-50 p-6 text-sm font-bold text-slate-500">분석 기록이 없어 기본 확인 항목으로 생성했습니다.</div>}</section><section className="mt-7 rounded-2xl bg-slate-900 p-6 text-white"><h2 className="text-xl font-black">이번 달 반드시 실천할 행동</h2><p className="mt-3 text-lg font-bold">{action}</p></section><section className="mt-7"><h2 className="text-xl font-black">수기 작성 4단계</h2><ol className="mt-4 grid gap-3 sm:grid-cols-2">{['수행할 작업을 구체적으로 적기', '가장 큰 위험의 시간과 위치 적기', '위험등급과 발생 조건 적기', '작업 전·중·후 실천행동 적기'].map((item, index) => <li key={item} className="rounded-xl border border-slate-200 p-4 text-sm font-bold"><b className="mr-2 text-orange-600">{index + 1}</b>{item}</li>)}</ol></section></article>
        <button type="button" onClick={() => window.print()} className="a4-controls w-full rounded-xl bg-orange-500 px-5 py-4 text-sm font-black text-white">A4 인쇄 / PDF 저장</button></div>;
};
export default A4EducationMaterial;
