import React, { useMemo, useState } from 'react';
import type { WorkerRecord } from '../types';
interface Props { workerRecords: WorkerRecord[]; }
const PptPdfOnePageSummary: React.FC<Props> = ({ workerRecords }) => {
    const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState('작업 전 위험요인을 확인하고 정해진 안전조치를 이행합니다.');
    const risks = useMemo(() => { const counts = new Map<string, number>(); workerRecords.forEach((item) => (item.weakAreas || []).forEach((risk) => counts.set(risk, (counts.get(risk) || 0) + 1))); return [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3).map(([risk]) => risk); }, [workerRecords]);
    return <div className="space-y-5 pb-16"><style>{`@media print{.summary-controls{display:none!important}.summary-sheet{box-shadow:none!important;border:0!important}}`}</style><section className="summary-controls rounded-3xl bg-gradient-to-br from-blue-800 to-indigo-700 p-6 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[0.16em]">Source Material Summary</p><h2 className="mt-2 text-2xl font-black">PPT/PDF 한장요약</h2><p className="mt-2 text-sm font-semibold text-blue-100">기존 현장 교육자료를 근로자용 핵심 브리핑으로 줄이는 독립 기능입니다.</p></section><section className="summary-controls grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 lg:grid-cols-2"><label className="flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-blue-200 bg-blue-50 text-center"><span className="text-sm font-black text-blue-800">PPT / PPTX / PDF 업로드</span><span className="mt-2 text-xs font-semibold text-blue-500">원본 교육자료를 선택해 한장요약 제목과 핵심 문구를 구성합니다.</span><input type="file" accept=".ppt,.pptx,.pdf" className="sr-only" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><label className="text-sm font-black">핵심 전달 문구<textarea value={message} onChange={(event) => setMessage(event.target.value)} rows={5} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-semibold" /></label></section><article className="summary-sheet mx-auto min-h-[260mm] w-full max-w-[210mm] rounded-2xl border border-slate-200 bg-white p-8 shadow-xl"><header className="border-b-4 border-blue-700 pb-5"><p className="text-sm font-black text-blue-700">PSI 현장 교육 한장요약</p><h1 className="mt-2 text-3xl font-black">{file ? file.name.replace(/\.(pptx?|pdf)$/i, '') : '교육자료를 업로드해 주세요'}</h1>{file && <p className="mt-2 text-xs font-bold text-slate-400">원본 {file.name} · {(file.size / 1024 / 1024).toFixed(1)}MB</p>}</header><section className="mt-7 rounded-2xl bg-blue-700 p-6 text-white"><p className="text-xs font-black text-blue-100">핵심 메시지</p><p className="mt-3 text-2xl font-black leading-9">{message}</p></section><section className="mt-7 grid gap-4 sm:grid-cols-3">{(risks.length ? risks : ['추락', '끼임', '보호구 미착용']).map((risk) => <div key={risk} className="rounded-2xl border border-slate-200 p-5 text-center"><p className="text-xs font-black text-slate-400">주요 위험</p><p className="mt-2 text-lg font-black">{risk}</p></div>)}</section><section className="mt-7"><h2 className="text-xl font-black">현장 실천 확인</h2><ul className="mt-4 space-y-3">{['작업 시작 전 오늘 작업과 위험요소 확인', '안전시설과 보호구 상태 직접 확인', '조건 변경 시 즉시 멈추고 관리자에게 알림'].map((item) => <li key={item} className="rounded-xl bg-slate-50 p-4 text-sm font-bold">• {item}</li>)}</ul></section></article><button type="button" onClick={() => window.print()} disabled={!file} className="summary-controls w-full rounded-xl bg-blue-700 px-5 py-4 text-sm font-black text-white disabled:opacity-40">한장요약 인쇄 / PDF 저장</button></div>;
};
export default PptPdfOnePageSummary;
