-- Privacy-first monthly archive receipts.
--
-- The PC archive remains the source of truth. These tables intentionally store
-- only a hash/count manifest and fixed-size, pseudonymous worker continuity
-- aggregates. Full risk records, OCR text, images and worker PII have no columns.

begin;

create table if not exists public.risk_archive_manifests (
    id bigint generated by default as identity primary key,
    organization_id text not null check (
        organization_id = btrim(organization_id)
        and char_length(organization_id) between 1 and 120
    ),
    site_id text not null check (
        site_id = btrim(site_id)
        and char_length(site_id) between 1 and 120
    ),
    archive_id text not null check (char_length(archive_id) between 6 and 96),
    schema_version text not null check (schema_version = 'psi-monthly-archive/v3'),
    period_month text not null check (period_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
    generation integer not null check (generation between 1 and 999999),
    record_count integer not null check (record_count between 1 and 10000000),
    worker_count integer not null check (worker_count between 0 and record_count),
    portable_worker_count integer not null check (portable_worker_count between 0 and worker_count),
    unresolved_worker_count integer not null check (
        unresolved_worker_count between 0 and worker_count
        and portable_worker_count + unresolved_worker_count = worker_count
    ),
    min_date date not null,
    max_date date not null check (max_date >= min_date),
    content_root_hash text not null check (content_root_hash ~ '^[0-9a-f]{64}$'),
    worker_summary_hash text not null check (worker_summary_hash ~ '^[0-9a-f]{64}$'),
    file_name text not null check (
        file_name = 'PSI_' || archive_id || '.json'
    ),
    byte_size bigint check (byte_size is null or byte_size > 0),
    archive_created_at timestamptz not null,
    verified_at timestamptz not null,
    received_at timestamptz not null default now(),
    constraint risk_archive_manifests_archive_scope_unique
        unique (organization_id, site_id, archive_id),
    constraint risk_archive_manifests_generation_unique
        unique (organization_id, site_id, period_month, generation),
    constraint risk_archive_manifests_dates_match_month check (
        to_char(min_date, 'YYYY-MM') = period_month
        and to_char(max_date, 'YYYY-MM') = period_month
        and verified_at >= archive_created_at
    ),
    constraint risk_archive_manifests_canonical_id check (
        archive_id = period_month || '-g' || lpad(generation::text, greatest(3, length(generation::text)), '0')
            || '-' || left(content_root_hash, 16)
    )
);

create index if not exists risk_archive_manifests_scope_month_idx
    on public.risk_archive_manifests (
        organization_id,
        site_id,
        period_month desc,
        generation desc
    );

create table if not exists public.worker_monthly_continuity (
    organization_id text not null,
    site_id text not null,
    period_month text not null check (period_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
    worker_uuid text not null check (
        char_length(worker_uuid) between 3 and 96
        and worker_uuid !~* '^WN-'
    ),
    assessment_count integer not null check (assessment_count > 0),
    first_assessment_date date not null,
    last_assessment_date date not null check (last_assessment_date >= first_assessment_date),
    average_score smallint not null check (average_score between 0 and 100),
    minimum_score smallint not null check (minimum_score between 0 and 100),
    latest_score smallint not null check (latest_score between 0 and 100),
    latest_safety_level text not null check (latest_safety_level in ('초급', '중급', '고급')),
    attention_count integer not null check (attention_count between 0 and assessment_count),
    approved_count integer not null check (approved_count between 0 and assessment_count),
    archive_id text not null,
    archive_generation integer not null check (archive_generation between 1 and 999999),
    archive_hash text not null check (archive_hash ~ '^[0-9a-f]{64}$'),
    updated_at timestamptz not null default now(),
    primary key (organization_id, site_id, period_month, worker_uuid),
    constraint worker_monthly_continuity_archive_fk
        foreign key (organization_id, site_id, archive_id)
        references public.risk_archive_manifests (organization_id, site_id, archive_id)
        on delete cascade,
    constraint worker_monthly_continuity_dates_match_month check (
        to_char(first_assessment_date, 'YYYY-MM') = period_month
        and to_char(last_assessment_date, 'YYYY-MM') = period_month
    )
);

create index if not exists worker_monthly_continuity_worker_idx
    on public.worker_monthly_continuity (worker_uuid, period_month desc);

alter table public.risk_archive_manifests enable row level security;
alter table public.risk_archive_manifests force row level security;
alter table public.worker_monthly_continuity enable row level security;
alter table public.worker_monthly_continuity force row level security;

revoke all on table public.risk_archive_manifests from public, anon, authenticated;
revoke all on table public.worker_monthly_continuity from public, anon, authenticated;
grant select on table public.risk_archive_manifests to service_role;
grant select on table public.worker_monthly_continuity to service_role;

create or replace function public.psi_register_monthly_archive(
    p_organization_id text,
    p_site_id text,
    p_manifest jsonb,
    p_worker_summaries jsonb
)
returns table (
    archive_id text,
    period_month text,
    generation integer,
    content_root_hash text,
    worker_summary_count integer,
    continuity_is_current boolean,
    received_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_required_manifest_keys constant text[] := array[
        'schema_version', 'archive_id', 'period_month', 'generation', 'file_name',
        'archive_created_at', 'record_count', 'worker_count', 'portable_worker_count',
        'unresolved_worker_count', 'min_date', 'max_date', 'content_root_hash',
        'byte_size', 'verified_at'
    ];
    v_required_summary_keys constant text[] := array[
        'worker_uuid', 'assessment_count', 'first_assessment_date',
        'last_assessment_date', 'average_score', 'minimum_score', 'latest_score',
        'latest_safety_level', 'attention_count', 'approved_count'
    ];
    v_existing public.risk_archive_manifests%rowtype;
    v_generation_archive_id text;
    v_previous_max_generation integer;
    v_summary jsonb;
    v_summary_count integer;
    v_assessment_total bigint;
    v_worker_summary_hash text;
    v_received_at timestamptz;
begin
    if coalesce(btrim(p_organization_id), '') = ''
       or char_length(p_organization_id) > 120
       or coalesce(btrim(p_site_id), '') = ''
       or char_length(p_site_id) > 120 then
        raise exception using errcode = '22023', message = 'invalid archive scope';
    end if;

    if jsonb_typeof(p_manifest) is distinct from 'object'
       or jsonb_typeof(p_worker_summaries) is distinct from 'array' then
        raise exception using errcode = '22023', message = 'invalid archive payload type';
    end if;

    if not (p_manifest ?& v_required_manifest_keys)
       or exists (
            select 1
              from jsonb_object_keys(p_manifest) as supplied(key)
             where not (supplied.key = any(v_required_manifest_keys))
       ) or exists (
            select 1 from jsonb_each(p_manifest) as supplied(key, value)
             where supplied.key <> 'byte_size' and supplied.value = 'null'::jsonb
       ) then
        raise exception using errcode = '22023', message = 'invalid archive manifest fields';
    end if;

    if p_manifest->>'schema_version' <> 'psi-monthly-archive/v3'
       or coalesce(p_manifest->>'archive_id', '') !~ '^[[:alnum:]_.:-]{6,96}$'
       or coalesce(p_manifest->>'period_month', '') !~ '^\d{4}-(0[1-9]|1[0-2])$'
       or lower(coalesce(p_manifest->>'content_root_hash', '')) !~ '^[0-9a-f]{64}$'
       or p_manifest->>'file_name' <> 'PSI_' || (p_manifest->>'archive_id') || '.json' then
        raise exception using errcode = '22023', message = 'invalid archive manifest value';
    end if;

    if (p_manifest->>'generation')::integer not between 1 and 999999
       or (p_manifest->>'record_count')::integer not between 1 and 10000000
       or (p_manifest->>'worker_count')::integer not between 0 and (p_manifest->>'record_count')::integer
       or (p_manifest->>'portable_worker_count')::integer not between 0 and (p_manifest->>'worker_count')::integer
       or (p_manifest->>'unresolved_worker_count')::integer not between 0 and (p_manifest->>'worker_count')::integer
       or (p_manifest->>'portable_worker_count')::integer
            + (p_manifest->>'unresolved_worker_count')::integer
            <> (p_manifest->>'worker_count')::integer
       or to_char((p_manifest->>'min_date')::date, 'YYYY-MM') <> p_manifest->>'period_month'
       or to_char((p_manifest->>'max_date')::date, 'YYYY-MM') <> p_manifest->>'period_month'
       or (p_manifest->>'max_date')::date < (p_manifest->>'min_date')::date
       or (p_manifest->>'verified_at')::timestamptz < (p_manifest->>'archive_created_at')::timestamptz
       or (nullif(p_manifest->>'byte_size', ''))::bigint <= 0 then
        raise exception using errcode = '22023', message = 'invalid archive manifest aggregate';
    end if;

    v_summary_count := jsonb_array_length(p_worker_summaries);
    if v_summary_count > 5000
       or v_summary_count <> (p_manifest->>'portable_worker_count')::integer then
        raise exception using errcode = '22023', message = 'worker summary count mismatch';
    end if;

    for v_summary in select value from jsonb_array_elements(p_worker_summaries)
    loop
        if jsonb_typeof(v_summary) is distinct from 'object'
           or not (v_summary ?& v_required_summary_keys)
           or exists (
                select 1
                  from jsonb_object_keys(v_summary) as supplied(key)
                 where not (supplied.key = any(v_required_summary_keys))
           ) or exists (
                select 1 from jsonb_each(v_summary) as supplied(key, value)
                 where supplied.value = 'null'::jsonb
           ) then
            raise exception using errcode = '22023', message = 'invalid worker summary fields';
        end if;

        if (
                coalesce(v_summary->>'worker_uuid', '') !~* '^(WP-|WU-)[A-Z0-9._:-]{1,92}$'
                and coalesce(v_summary->>'worker_uuid', '') !~* '^[0-9A-F]{8}-[0-9A-F]{4}-[1-5][0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$'
           )
           or coalesce(v_summary->>'worker_uuid', '') ~* '^WN-'
           or (v_summary->>'assessment_count')::integer not between 1 and (p_manifest->>'record_count')::integer
           or (v_summary->>'average_score')::integer not between 0 and 100
           or (v_summary->>'minimum_score')::integer not between 0 and 100
           or (v_summary->>'latest_score')::integer not between 0 and 100
           or (v_summary->>'minimum_score')::integer > (v_summary->>'average_score')::integer
           or (v_summary->>'minimum_score')::integer > (v_summary->>'latest_score')::integer
           or v_summary->>'latest_safety_level' not in ('초급', '중급', '고급')
           or (v_summary->>'attention_count')::integer not between 0 and (v_summary->>'assessment_count')::integer
           or (v_summary->>'approved_count')::integer not between 0 and (v_summary->>'assessment_count')::integer
           or to_char((v_summary->>'first_assessment_date')::date, 'YYYY-MM') <> p_manifest->>'period_month'
           or to_char((v_summary->>'last_assessment_date')::date, 'YYYY-MM') <> p_manifest->>'period_month'
           or (v_summary->>'last_assessment_date')::date < (v_summary->>'first_assessment_date')::date
           or (v_summary->>'first_assessment_date')::date < (p_manifest->>'min_date')::date
           or (v_summary->>'last_assessment_date')::date > (p_manifest->>'max_date')::date then
            raise exception using errcode = '22023', message = 'invalid worker summary value';
        end if;
    end loop;

    if (
        select count(*) <> count(distinct upper(value->>'worker_uuid'))
          from jsonb_array_elements(p_worker_summaries)
    ) then
        raise exception using errcode = '22023', message = 'duplicate worker summary';
    end if;

    select coalesce(sum((value->>'assessment_count')::bigint), 0)
      into v_assessment_total
      from jsonb_array_elements(p_worker_summaries);
    if v_assessment_total + (p_manifest->>'unresolved_worker_count')::integer > (p_manifest->>'record_count')::integer
       or ((p_manifest->>'unresolved_worker_count')::integer = 0
           and v_assessment_total <> (p_manifest->>'record_count')::integer) then
        raise exception using errcode = '22023', message = 'worker assessment total mismatches record count';
    end if;

    -- Keep only a digest, not historical summary JSON. This makes retries
    -- immutable even after newer generations replace the current snapshot.
    select encode(sha256(convert_to(coalesce(jsonb_agg(
        jsonb_set(value, '{worker_uuid}', to_jsonb(upper(value->>'worker_uuid')))
        order by upper(value->>'worker_uuid')
    ), '[]'::jsonb)::text, 'UTF8')), 'hex')
      into v_worker_summary_hash
      from jsonb_array_elements(p_worker_summaries);

    -- Serialize one organization/site/month so generation conflicts and the
    -- current continuity snapshot cannot race each other.
    perform pg_advisory_xact_lock(
        hashtext(jsonb_build_array(p_organization_id, p_site_id, p_manifest->>'period_month')::text)
    );

    select *
      into v_existing
      from public.risk_archive_manifests as m
     where m.organization_id = p_organization_id
       and m.site_id = p_site_id
       and m.archive_id = p_manifest->>'archive_id';

    if found then
        if v_existing.period_month <> p_manifest->>'period_month'
           or v_existing.generation <> (p_manifest->>'generation')::integer
           or v_existing.content_root_hash <> lower(p_manifest->>'content_root_hash')
           or v_existing.record_count <> (p_manifest->>'record_count')::integer
           or v_existing.worker_count <> (p_manifest->>'worker_count')::integer
           or v_existing.portable_worker_count <> (p_manifest->>'portable_worker_count')::integer
           or v_existing.unresolved_worker_count <> (p_manifest->>'unresolved_worker_count')::integer
           or v_existing.min_date <> (p_manifest->>'min_date')::date
           or v_existing.max_date <> (p_manifest->>'max_date')::date
           or v_existing.worker_summary_hash <> v_worker_summary_hash then
            raise exception using errcode = '23505', message = 'archive receipt id conflict';
        end if;

        select max(m.generation) into v_previous_max_generation
          from public.risk_archive_manifests as m
         where m.organization_id = p_organization_id
           and m.site_id = p_site_id
           and m.period_month = v_existing.period_month;

        return query
        select v_existing.archive_id,
               v_existing.period_month,
               v_existing.generation,
               v_existing.content_root_hash,
               v_existing.portable_worker_count,
               v_existing.generation = v_previous_max_generation,
               v_existing.received_at;
        return;
    end if;

    select m.archive_id
      into v_generation_archive_id
      from public.risk_archive_manifests as m
     where m.organization_id = p_organization_id
       and m.site_id = p_site_id
       and m.period_month = p_manifest->>'period_month'
       and m.generation = (p_manifest->>'generation')::integer;
    if found then
        raise exception using errcode = '23505', message = 'archive generation conflict';
    end if;

    select max(m.generation)
      into v_previous_max_generation
      from public.risk_archive_manifests as m
     where m.organization_id = p_organization_id
       and m.site_id = p_site_id
       and m.period_month = p_manifest->>'period_month';

    insert into public.risk_archive_manifests (
        organization_id,
        site_id,
        archive_id,
        schema_version,
        period_month,
        generation,
        record_count,
        worker_count,
        portable_worker_count,
        unresolved_worker_count,
        min_date,
        max_date,
        content_root_hash,
        worker_summary_hash,
        file_name,
        byte_size,
        archive_created_at,
        verified_at
    ) values (
        p_organization_id,
        p_site_id,
        p_manifest->>'archive_id',
        p_manifest->>'schema_version',
        p_manifest->>'period_month',
        (p_manifest->>'generation')::integer,
        (p_manifest->>'record_count')::integer,
        (p_manifest->>'worker_count')::integer,
        (p_manifest->>'portable_worker_count')::integer,
        (p_manifest->>'unresolved_worker_count')::integer,
        (p_manifest->>'min_date')::date,
        (p_manifest->>'max_date')::date,
        lower(p_manifest->>'content_root_hash'),
        v_worker_summary_hash,
        p_manifest->>'file_name',
        (nullif(p_manifest->>'byte_size', ''))::bigint,
        (p_manifest->>'archive_created_at')::timestamptz,
        (p_manifest->>'verified_at')::timestamptz
    )
    returning risk_archive_manifests.received_at into v_received_at;

    -- A late receipt for an older generation is retained for audit but must not
    -- roll the month's current worker continuity snapshot backwards.
    if (p_manifest->>'generation')::integer >= coalesce(v_previous_max_generation, 0) then
        delete from public.worker_monthly_continuity as c
         where c.organization_id = p_organization_id
           and c.site_id = p_site_id
           and c.period_month = p_manifest->>'period_month';

        insert into public.worker_monthly_continuity (
            organization_id,
            site_id,
            period_month,
            worker_uuid,
            assessment_count,
            first_assessment_date,
            last_assessment_date,
            average_score,
            minimum_score,
            latest_score,
            latest_safety_level,
            attention_count,
            approved_count,
            archive_id,
            archive_generation,
            archive_hash
        )
        select
            p_organization_id,
            p_site_id,
            p_manifest->>'period_month',
            upper(value->>'worker_uuid'),
            (value->>'assessment_count')::integer,
            (value->>'first_assessment_date')::date,
            (value->>'last_assessment_date')::date,
            (value->>'average_score')::smallint,
            (value->>'minimum_score')::smallint,
            (value->>'latest_score')::smallint,
            value->>'latest_safety_level',
            (value->>'attention_count')::integer,
            (value->>'approved_count')::integer,
            p_manifest->>'archive_id',
            (p_manifest->>'generation')::integer,
            lower(p_manifest->>'content_root_hash')
          from jsonb_array_elements(p_worker_summaries);
    end if;

    return query
    select p_manifest->>'archive_id',
           p_manifest->>'period_month',
           (p_manifest->>'generation')::integer,
           lower(p_manifest->>'content_root_hash'),
           v_summary_count,
           (p_manifest->>'generation')::integer >= coalesce(v_previous_max_generation, 0),
           v_received_at;
end;
$$;

revoke all on function public.psi_register_monthly_archive(text, text, jsonb, jsonb)
    from public, anon, authenticated;
grant execute on function public.psi_register_monthly_archive(text, text, jsonb, jsonb)
    to service_role;

notify pgrst, 'reload schema';

commit;
