-- Durable, fail-closed quota and paid-OCR approval gate.
-- This migration is intentionally independent from unrelated PSI tables.

begin;

create table if not exists public.api_security_events (
    id bigint generated by default as identity primary key,
    scope text not null,
    client_key_hash text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists api_security_events_scope_client_created_idx
    on public.api_security_events (scope, client_key_hash, created_at desc);

alter table public.api_security_events enable row level security;
revoke all on table public.api_security_events from public, anon, authenticated;
grant select, insert, delete on table public.api_security_events to service_role;

create table if not exists public.api_usage_events (
    id bigint generated by default as identity primary key,
    scope text not null,
    client_key_hash text not null,
    outcome text not null check (outcome in ('success', 'failure', 'blocked')),
    resource_id text,
    latency_ms integer,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists api_usage_events_scope_created_idx
    on public.api_usage_events (scope, created_at desc);

alter table public.api_usage_events enable row level security;
revoke all on table public.api_usage_events from public, anon, authenticated;
grant select, insert on table public.api_usage_events to service_role;
grant usage, select on sequence public.api_usage_events_id_seq to service_role;

create or replace function public.psi_consume_api_quota(
    p_scope text,
    p_client_key_hash text,
    p_max_requests integer,
    p_window_seconds integer,
    p_metadata jsonb default '{}'::jsonb
)
returns table(allowed boolean, current_count integer, retry_after_seconds integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_count integer;
    v_oldest timestamptz;
    v_window interval;
begin
    if coalesce(trim(p_scope), '') = ''
       or coalesce(trim(p_client_key_hash), '') = ''
       or p_max_requests < 1
       or p_window_seconds < 1 then
        raise exception 'invalid quota arguments';
    end if;

    perform pg_advisory_xact_lock(hashtext(p_scope || ':' || p_client_key_hash));
    v_window := make_interval(secs => p_window_seconds);

    select count(*)::integer, min(created_at)
      into v_count, v_oldest
      from public.api_security_events
     where scope = p_scope
       and client_key_hash = p_client_key_hash
       and created_at >= now() - v_window;

    if v_count >= p_max_requests then
        return query select false, v_count,
            greatest(1, ceil(extract(epoch from ((v_oldest + v_window) - now())))::integer);
        return;
    end if;

    insert into public.api_security_events(scope, client_key_hash, metadata)
    values (p_scope, p_client_key_hash, coalesce(p_metadata, '{}'::jsonb));

    return query select true, v_count + 1, 0;
end;
$$;

revoke all on function public.psi_consume_api_quota(text, text, integer, integer, jsonb)
    from public, anon, authenticated;
grant execute on function public.psi_consume_api_quota(text, text, integer, integer, jsonb)
    to service_role;

notify pgrst, 'reload schema';

commit;
